namespace VTS.QLNS.CTC.Utility.Enum
{
    public enum BhQuyeToanChiNamType
    {
        PRINT_BAOCAOQUYETTOANCHIBHXH = 1,
        PRINT_QUYETTOANCHIBHXH = 2,
        PRINT_NHANVAQUYETTOANKINHPHIBHXH = 3
    }

    public enum BhThamDinhQuyetToanType
    {
        PRINT_BAO_CAO_THAM_DINH_QUYET_TOAN_THU_CHI,
        PRINT_THONG_BAO_PHE_DUYET_QUYET_TOAN_NAM_TONG_HOP_THU_CHI,
        PRINT_BAO_CAO_TONG_HOP_QUYET_TOAN_THU_CHI_BHXH_BHYT_BHTN,
        PRINT_BAO_CAO_QUYET_TOAN_THU_BHXH_BHYT_BHTN,
        PRINT_BAO_CAO_QUYET_TOAN_THU_BHYT_THAN_NHAN,
        PRINT_BAO_CAO_QUYET_TOAN_CHI_CHE_DO_BHXH,
        PRINT_BAO_CAO_CHI_TIEU_QUYET_TOAN_KINH_PHI_QUAN_LY_BHXH_BHYT,
        PRINT_BAO_CAO_CHI_TIEU_QUYET_TOAN_KINH_PHI_KCB_QUAN_Y_DON_VI,
        PRINT_BAO_CAO_CHI_TIEU_QUYET_TOAN_KINH_PHI_KCB_TRUONG_SA_DK,
        PRINT_BAO_CAO_CHI_TIEU_QUYET_TOAN_KINH_PHI_KCB_HSSV_NLD,
        PRINT_BAO_CAO_CHI_TIEU_QUYET_TOAN_KINH_PHI_MUA_SAM_TTBYT,
        PRINT_BAO_CAO_DU_TOAN_KINH_PHI_BHXH_BHYT_BHTN_CHUYEN_NAM_SAU,
        PRINT_CAN_CU_TRICH_QUY_BHXH_SANG_DONG_BHYT
    }
}
