IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='BH_QTC_Quy_KinhPhiQuanLy_ChiTiet' AND COLUMN_NAME='sGhiChu')
BEGIN ALTER TABLE BH_QTC_Quy_KinhPhiQuanLy_ChiTiet ADD sGhiChu nvarchar(max);
END;