IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '651732B4-8D47-4A31-9BE7-33906AF647E5')
DELETE FROM [dbo].[DM_ChuKy] where Id = '651732B4-8D47-4A31-9BE7-33906AF647E5'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '74616964-5bbd-47ff-9b53-55c58614f923')
DELETE FROM [dbo].[DM_ChuKy] where Id = '74616964-5bbd-47ff-9b53-55c58614f923'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'74616964-5bbd-47ff-9b53-55c58614f923', 1, N'KTCT', N'KT. CỤC TRƯỞNG', N'KTCT', N'KT. CỤC TRƯỞNG', N'NLTT', N'NGƯỜI LẬP THÔNG TRI', N'NLTT', N'NGƯỜI LẬP THÔNG TRI', N'NLTT', N'NGƯỜI LẬP THÔNG TRI', NULL, NULL, CAST(N'2023-06-28T15:58:02.990' AS DateTime), NULL, NULL, 1, N'rptBHYT_KHTM_ChiTiet', NULL, N'rptBHYT_KHTM_ChiTiet', NULL, NULL, NULL, NULL, NULL, N'KHTM_BHYT_THANNHAN', NULL, N'Báo cáo chi tiết thu BHYT thân nhân', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'KẾ HOẠCH MUA THẺ BẢO HIỂM Y TẾ THÂN NHÂN QUÂN NHÂN; THÂN NHÂN CƠ YẾU; THÂN NHÂN CN&VCQP; HS; SV;HVQS XÃ, PHƯỜNG; HV ĐÀO TẠO SĨ QUAN DỰ BỊ; HV QUỐC TẾ NĂM 20233', NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = 'F5E824C6-25A5-46E7-B1E3-FCD3452EF413')
DELETE FROM [dbo].[DM_ChuKy] where Id = 'F5E824C6-25A5-46E7-B1E3-FCD3452EF413'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '26a33b24-6905-4fad-8ccf-53df681ccf9a')
DELETE FROM [dbo].[DM_ChuKy] where Id = '26a33b24-6905-4fad-8ccf-53df681ccf9a'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'26a33b24-6905-4fad-8ccf-53df681ccf9a', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, N'rpt_BHXH_CPBS_QN', NULL, N'rpt_BHXH_CPBS_QN', NULL, NULL, NULL, NULL, NULL, N'CAP_BOSUNG_KCB_BHYT', NULL, N'Báo cáo kế hoạch cấp bổ sung KP KCB BHYT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'KẾ HOẠCH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = 'C0C07AF2-05B7-454A-8ED1-2008DDBD722D')
DELETE FROM [dbo].[DM_ChuKy] where Id = 'C0C07AF2-05B7-454A-8ED1-2008DDBD722D'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '5196401d-d8a6-40ae-8f98-581da7a36e64')
DELETE FROM [dbo].[DM_ChuKy] where Id = '5196401d-d8a6-40ae-8f98-581da7a36e64'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'5196401d-d8a6-40ae-8f98-581da7a36e64', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, N'rpt_BHXH_CPBS_THONG_TRI', NULL, N'rpt_BHXH_CPBS_THONG_TRI', NULL, NULL, NULL, NULL, NULL, N'CAP_BOSUNG_KCB_BHYT', NULL, N'Thông tri cấp bổ sung KP KCB BHYT - chi tiết đơn vị', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'THÔNG TRI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '0A487C2A-FAE4-4981-AEE5-A63F85BFAFF8')
DELETE FROM [dbo].[DM_ChuKy] where Id = '0A487C2A-FAE4-4981-AEE5-A63F85BFAFF8'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '9d3529f0-edab-4f19-8ee8-2d66e00dd562')
DELETE FROM [dbo].[DM_ChuKy] where Id = '9d3529f0-edab-4f19-8ee8-2d66e00dd562'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'9d3529f0-edab-4f19-8ee8-2d66e00dd562', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, N'rpt_BHXH_CPBS_TONG_HOP_THONG_TRI', NULL, N'rpt_BHXH_CPBS_TONG_HOP_THONG_TRI', NULL, NULL, NULL, NULL, NULL, N'CAP_BOSUNG_KCB_BHYT', NULL, N'Thông tri cấp bổ sung KP KCB BHYT - tổng hợp đơn vị', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'THÔNG TRI TỔNG HỢP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO


IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '37E9CF29-BF80-47DC-B204-03C3974299D4')
DELETE FROM [dbo].[DM_ChuKy] where Id = '37E9CF29-BF80-47DC-B204-03C3974299D4'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'37E9CF29-BF80-47DC-B204-03C3974299D4', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, N'rptBH_QuyetToanQuy_BaoCaoQuyetToanChiCacCheDoBHXH', NULL, N'rptBH_QuyetToanQuy_BaoCaoQuyetToanChiCacCheDoBHXH', NULL, NULL, NULL, NULL, NULL, N'QTC_CHEDOBHXH_QUY', NULL, N'Báo cáo quyết toán chi chế độ BHXH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '6C397BAD-D861-4B66-A9EB-BDAC0288108B')
DELETE FROM [dbo].[DM_ChuKy] where Id = '6C397BAD-D861-4B66-A9EB-BDAC0288108B'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '82051fa3-60d1-4cfc-8aee-265649168095')
DELETE FROM [dbo].[DM_ChuKy] where Id = '82051fa3-60d1-4cfc-8aee-265649168095'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'82051fa3-60d1-4cfc-8aee-265649168095', 1, N'', N'Người lập biểu', NULL, N'Trưởng phòng (ban) Tài chính', NULL, N'Thủ trưởng đơn vị', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, N'rptBHXH_DTT_DC_DTT_ChiTiet', NULL, N'rptBHXH_DTT_DC_DTT_ChiTiet', NULL, NULL, NULL, NULL, NULL, N'DIEUCHINH_DUTOAN_THU', NULL, N'Báo cáo điều chỉnh dự toán thu BHXH, BHYT, BHTN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'BÁO CÁO ĐIỀU CHỈNH DỰ TOÁN THU BHXH, BHYT, BHTN NĂM ....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '05F71EB0-3E32-469A-9A1A-D65658B41A0B')
DELETE FROM [dbo].[DM_ChuKy] where Id = '05F71EB0-3E32-469A-9A1A-D65658B41A0B'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '3e762a84-ad1b-4540-95fc-8d81a9c3ab59')
DELETE FROM [dbo].[DM_ChuKy] where Id = '3e762a84-ad1b-4540-95fc-8d81a9c3ab59'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'3e762a84-ad1b-4540-95fc-8d81a9c3ab59', 1, N'KTCT', N'KT. CỤC TRƯỞNG', N'KTCT', N'KT. CỤC TRƯỞNG', N'NLTT', N'NGƯỜI LẬP THÔNG TRI
NGƯỜI LẬP THÔNG TRI', NULL, NULL, NULL, NULL, NULL, NULL, CAST(N'2023-06-28T15:58:02.990' AS DateTime), NULL, NULL, 1, N'rptBHXH_DU_TOAN_THU_BHXH', NULL, N'rptBHXH_DU_TOAN_THU_BHXH', NULL, NULL, NULL, NULL, NULL, N'KHT_BHXH_BHYT_BHTN', NULL, N'Dự toán thu BHXH - PL II', N'TLBCTTLL', N'Đại tá Hoàng Đạo Thúy', N'TTBNG', N'Đại tá Hà Văn Lâu', N'BTTU - Nguyễn Mạnh Cường', N'Đại úy Nguyễn Mạnh Cường', NULL, NULL, NULL, NULL, NULL, NULL, N'PCT',  N'PHÓ CỤC TRƯỞNG', N'Nguyễn Văn QUyết', N'Cao văn Mai', N'NTT', N'NGƯỜI THANH TOÁN', NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'DỰ TOÁN THU BẢO HIỂM XÃ HỘI NĂM', NULL, N'(Kèm theo Quyết định số: ... ... /QĐ-BQP ngày ...../...../... ...)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '7CD12D8C-D570-45B0-9EA8-3CED42AFB21E')
DELETE FROM [dbo].[DM_ChuKy] where Id = '7CD12D8C-D570-45B0-9EA8-3CED42AFB21E'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = 'b9e3bad7-df3b-47fb-a047-c15965091615')
DELETE FROM [dbo].[DM_ChuKy] where Id = 'b9e3bad7-df3b-47fb-a047-c15965091615'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'b9e3bad7-df3b-47fb-a047-c15965091615', 1, N'KTCT', N'KT. CỤC TRƯỞNG', N'KTCT', N'KT. CỤC TRƯỞNG', N'NLTT', N'NGƯỜI LẬP THÔNG TRI  NGƯỜI LẬP THÔNG TRI', NULL, NULL, NULL, NULL, NULL, NULL, CAST(N'2023-06-28T15:58:02.990' AS DateTime), NULL, NULL, 1, N'rptBHXH_DU_TOAN_THU_BHYT_NLD', NULL, N'rptBHXH_DU_TOAN_THU_BHYT_NLD', NULL, NULL, NULL, NULL, NULL, N'KHT_BHXH_BHYT_BHTN', NULL, N'Dự toán thu BHYT người lao động - PL V', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'DỰ TOÁN THU BẢO HIỂM Y TẾ NGƯỜI LAO ĐỘNG NĂM ……', NULL, N'Kèm theo Quyết định số:……./QĐ-BQP ngày….. /…../……..', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '16A38A4E-6A96-4926-A132-10F4F3C9C9EA')
DELETE FROM [dbo].[DM_ChuKy] where Id = '16A38A4E-6A96-4926-A132-10F4F3C9C9EA'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '439eafc3-5f93-4fd9-91e5-557796a348ed')
DELETE FROM [dbo].[DM_ChuKy] where Id = '439eafc3-5f93-4fd9-91e5-557796a348ed'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'439eafc3-5f93-4fd9-91e5-557796a348ed', 1, N'KTCT', N'KT. CỤC TRƯỞNG', N'KTCT', N'KT. CỤC TRƯỞNG', N'NLTT', N'NGƯỜI LẬP THÔNG TRI  NGƯỜI LẬP THÔNG TRI', NULL, NULL, NULL, NULL, NULL, NULL, CAST(N'2023-06-28T15:58:02.990' AS DateTime), NULL, NULL, 1, N'rptBHXH_DU_TOAN_THU_BHYT_QUAN_NHAN', NULL, N'rptBHXH_DU_TOAN_THU_BHYT_QUAN_NHAN', NULL, NULL, NULL, NULL, NULL, N'KHT_BHXH_BHYT_BHTN', NULL, N'Dự toán thu BHYT quân nhân - PL IV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'DỰ TOÁN THU BẢO HIỂM Y TẾ QUÂN NHÂN NĂM …….', NULL, N'(Kèm theo Quyết định số:……./QĐ-BQP ngày….. /…../……..)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '97599502-a468-4454-aab8-519c624eb719')
DELETE FROM [dbo].[DM_ChuKy] where Id = '97599502-a468-4454-aab8-519c624eb719'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '5ca195fa-c7a9-42a6-a2e4-d6507eab86ec')
DELETE FROM [dbo].[DM_ChuKy] where Id = '5ca195fa-c7a9-42a6-a2e4-d6507eab86ec'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'5ca195fa-c7a9-42a6-a2e4-d6507eab86ec', 1, N'NL', N'NGƯỜI LẬP', N'TPTC', N'TRƯỞNG PHÒNG (BAN) TÀI CHÍNH ', N'TTDV', N'THỦ TRƯỞNG ĐƠN VỊ ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, N'rptBHXH_KHC_QLKP_ChiTiet', NULL, N'rptBHXH_KHC_QLKP_ChiTiet', NULL, NULL, NULL, NULL, NULL, N'KHC_KINHPHIQUANLY', NULL, N'Báo cáo chi tiết kế hoạch chi kinh phí quản lý BHXH, BHYT', N'TTBNG', N'Đại tá Hà Văn Lâu', N'BTTU - Nguyễn Mạnh Cường', N'Đại úy Nguyễn Mạnh Cường', N'BTTU - Nguyễn Mạnh Cường', N'Đại úy Nguyễn Mạnh Cường', NULL, NULL, NULL, NULL, NULL, NULL, N'NL', N'NGƯỜI LẬP', N'TPTC', N'TRƯỞNG PHÒNG (BAN) TÀI CHÍNH ', N'TTDV', N'THỦ TRƯỞNG ĐƠN VỊ ', NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'KẾ HOẠCH CHI KINH PHÍ QUẢN LÝ BHXH, BHYT, BHTN NĂM ...................', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '81B944FA-ED8E-40FF-A630-22F89612ACCC')
DELETE FROM [dbo].[DM_ChuKy] where Id = '81B944FA-ED8E-40FF-A630-22F89612ACCC'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '821816a8-cbc2-4f95-83df-b07d570c7fa8')
DELETE FROM [dbo].[DM_ChuKy] where Id = '821816a8-cbc2-4f95-83df-b07d570c7fa8'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'821816a8-cbc2-4f95-83df-b07d570c7fa8', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, N'rptBHXH_KHC_QLKP_TongHop', NULL, N'rptBHXH_KHC_QLKP_TongHop', NULL, NULL, NULL, NULL, NULL, N'KHC_KINHPHIQUANLY', NULL, N'Dự toán chi kinh phí quản lý BHXH, BHYT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'Phụ lục VIII', NULL, N'DỰ TOÁN CHI KINH PHÍ QUẢN LÝ BHXH, BHYT NĂM ......', N'(Kèm theo Quyết định số: .... .../QĐ-BQP ngày....../......../..............)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = 'E2D8CC8A-C00C-4FCC-9D23-B228A327287B')
DELETE FROM [dbo].[DM_ChuKy] where Id = 'E2D8CC8A-C00C-4FCC-9D23-B228A327287B'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = 'e2e83d55-2032-491c-adf4-8baddd301e3a')
DELETE FROM [dbo].[DM_ChuKy] where Id = 'e2e83d55-2032-491c-adf4-8baddd301e3a'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'e2e83d55-2032-491c-adf4-8baddd301e3a', 1, N'NTT', N'NGƯỜI THANH TOÁN', N'NTT', N'NGƯỜI THANH TOÁN', N'NTT', N'NGƯỜI THANH TOÁN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, N'rptBHXH_KHC_TongHop', NULL, N'rptBHXH_KHC_TongHop', NULL, NULL, NULL, NULL, NULL, N'KHC_CHEDOBHXH', NULL, N'Dự toán chi kinh phí quản lý BHXH, BHYT - PL VIII', N'PCT - Đỗ Đình Mỹ', N'Đại tá Đỗ Đình Mỹ 7', NULL, NULL, N'PCT - Đỗ Đình Mỹ', N'Đại tá Đỗ Đình Mỹ 7', NULL, NULL, NULL, NULL, NULL, NULL, N'Nguyễn Văn QUyết', N'Cao văn Mai', N'Nguyễn Văn QUyết', N'Cao văn Mai', N'Nguyễn Văn QUyết', N'Cao văn Mai', NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'Phụ luc VII', NULL, N'DỰ TOÁN CHI CÁC CHẾ ĐỘ BẢO HIỂM XÃ HỘI NĂM ..........', N'(Kèm theo quyết định số: ......../QĐ-BQP ngày ....../....../......)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '6A71FA7D-FC88-4207-836E-98EC52736D12')
DELETE FROM [dbo].[DM_ChuKy] where Id = '6A71FA7D-FC88-4207-836E-98EC52736D12'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '04c2e7de-e969-40b1-b158-3b760aba9d48')
DELETE FROM [dbo].[DM_ChuKy] where Id = '04c2e7de-e969-40b1-b158-3b760aba9d48'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'04c2e7de-e969-40b1-b158-3b760aba9d48', 1, N'KTCT', N'KT. CỤC TRƯỞNG', N'KTCT', N'KT. CỤC TRƯỞNG', N'NLTT', N'NGƯỜI LẬP THÔNG TRI', NULL, NULL, NULL, NULL, NULL, NULL, CAST(N'2023-06-28T15:58:02.990' AS DateTime), NULL, NULL, 1, N'rptBHXH_KHT_ChiTiet', NULL, N'rptBHXH_KHT_ChiTiet', NULL, NULL, NULL, NULL, NULL, N'KHT_BHXH_BHYT_BHTN', NULL, N'Báo cáo chi tiết kế hoạch thu BHXH, BHYT, BHTN', N'TLBCTTLL', N'Đại tá Hoàng Đạo Thúy', N'TTBNG', N'Đại tá Hà Văn Lâu', N'BTTU - Nguyễn Mạnh Cường', N'Đại úy Nguyễn Mạnh Cường', NULL, NULL, NULL, NULL, NULL, NULL, N'PCT', N'PHÓ CỤC TRƯỞNG', N'Nguyễn Văn QUyết', N'Cao văn Mai', N'NTT', N'NGƯỜI THANH TOÁN', NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'KẾ HOẠCH THU BHXH, BHYT, BHTN NĂM 20233', NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '72544183-22B0-471E-A850-0AB80A9334FD')
DELETE FROM [dbo].[DM_ChuKy] where Id = '72544183-22B0-471E-A850-0AB80A9334FD'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = 'f5a30f49-3892-4f3e-9553-ca105902ccbe')
DELETE FROM [dbo].[DM_ChuKy] where Id = 'f5a30f49-3892-4f3e-9553-ca105902ccbe'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'f5a30f49-3892-4f3e-9553-ca105902ccbe', 1, N'KTCT', N'KT. CỤC TRƯỞNG', N'KTCT', N'KT. CỤC TRƯỞNG', N'NLTT', N'NGƯỜI LẬP THÔNG TRI', N'NLTT', N'NGƯỜI LẬP THÔNG TRI', NULL, NULL, NULL, NULL, CAST(N'2023-06-28T15:58:02.990' AS DateTime), NULL, NULL, 1, N'rptBHYT_KHTM_DuToanThu_HSSV', NULL, N'rptBHYT_KHTM_DuToanThu_HSSV', NULL, NULL, NULL, NULL, NULL, N'KHTM_BHYT_THANNHAN', NULL, N'Dự toán thu BHYT HSSV, HVQS Xã phường, SQDB - PL VII', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'DỰ TOÁN THU BẢO HIỂM Y TẾ HSSV, HVQS XÃ PHƯỜNG VÀ SĨ QUAN DỰ BỊ NĂM 2023', NULL, N'(Kèm theo Quyết định số: ... ... /QĐ-BQP ngày ...../...../... ...)', NULL, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, NULL, NULL, NULL)
END
GO

IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '1BA2E6C2-35C8-4B53-B3B0-22E9A4B71FD0')
DELETE FROM [dbo].[DM_ChuKy] where Id = '1BA2E6C2-35C8-4B53-B3B0-22E9A4B71FD0'
IF EXISTS (SELECT * FROM [dbo].[DM_ChuKy] where Id = '6801c19e-46e5-48bb-ac74-c24872b39dc2')
DELETE FROM [dbo].[DM_ChuKy] where Id = '6801c19e-46e5-48bb-ac74-c24872b39dc2'
BEGIN
INSERT [dbo].[DM_ChuKy] ([Id], [bDanhSach], [ChucDanh1], [ChucDanh1_MoTa], [ChucDanh2], [ChucDanh2_MoTa], [ChucDanh3], [ChucDanh3_MoTa], [ChucDanh4], [ChucDanh4_MoTa], [ChucDanh5], [ChucDanh5_MoTa], [ChucDanh6], [ChucDanh6_MoTa], [DateCreated], [DateModified], [INamLamViec], [iTrangThai], [Id_Code], [Id_Old_Type], [Id_Type], [KyHieu], [Log], [MoTa], [sKinhGuiCQTTBQP], [sKinhGuiKBNN], [sLoai], [Tag], [Ten], [Ten1], [Ten1_MoTa], [Ten2], [Ten2_MoTa], [Ten3], [Ten3_MoTa], [Ten4], [Ten4_MoTa], [Ten5], [Ten5_MoTa], [Ten6], [Ten6_MoTa], [ThuaLenh1], [ThuaLenh1_MoTa], [ThuaLenh2], [ThuaLenh2_MoTa], [ThuaLenh3], [ThuaLenh3_MoTa], [ThuaLenh4], [ThuaLenh4_MoTa], [ThuaLenh5], [ThuaLenh5_MoTa], [ThuaLenh6], [ThuaLenh6_MoTa], [TieuDe1], [TieuDe1_MoTa], [TieuDe2], [TieuDe2_MoTa], [TieuDe3_MoTa], [UserCreator], [UserModifier], [LoaiDVBanHanh1], [LoaiDVBanHanh2], [TenDVBanHanh1], [TenDVBanHanh2], [ThuaUyQuyen1], [ThuaUyQuyen1_MoTa], [ThuaUyQuyen2], [ThuaUyQuyen2_MoTa], [ThuaUyQuyen3], [ThuaUyQuyen3_MoTa]) VALUES (N'6801c19e-46e5-48bb-ac74-c24872b39dc2', 1, N'KTCT', N'KT. CỤC TRƯỞNG', N'KTCT', N'KT. CỤC TRƯỞNG', N'NLTT', N'NGƯỜI LẬP THÔNG TRI', N'NLTT', N'NGƯỜI LẬP THÔNG TRI', N'NLTT', N'NGƯỜI LẬP THÔNG TRI', NULL, NULL, CAST(N'2023-06-28T15:58:02.990' AS DateTime), NULL, NULL, 1, N'rptBHYT_KHTM_DuToanThu_Than_nhan', NULL, N'rptBHYT_KHTM_DuToanThu_Than_nhan', NULL, NULL, NULL, NULL, NULL, N'KHTM_BHYT_THANNHAN', NULL, N'Dự toán thu BHYT thân nhân - PL VI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'1', N'DỰ TOÁN THU BẢO HIỂM Y TẾ THÂN NHÂN NĂM 2023', NULL, N'(Kèm theo Quyết định số: ... ... /QĐ-BQP ngày ...../...../... ...)', NULL, NULL, NULL, NULL, NULL, N'', N'', NULL, NULL, NULL, NULL, NULL, NULL)
END
GO