  insert DanhMuc ([iID_MaDanhMuc]
      ,[iNamLamViec]
      ,[iThuTu]
      ,[iTrangThai]
      ,[Log]
      ,[NganSachNganh]
      ,[sGiaTri]
      ,[sMoTa]
      ,[sNguoiSua]
      ,[sNguoiTao]
      ,[sTen]
      ,[sType]
      ,[Tag]) values ('MIGRATE_EXCEPT', 2023, 999, 1, NULL, NULL, 2023, N'Không migrate dữ liệu của năm', 'Admin', 'Admin', 'Migrate Except', 'DM_CauHinh', NULL)

  insert DanhMuc ([iID_MaDanhMuc]
      ,[iNamLamViec]
      ,[iThuTu]
      ,[iTrangThai]
      ,[Log]
      ,[NganSachNganh]
      ,[sGiaTri]
      ,[sMoTa]
      ,[sNguoiSua]
      ,[sNguoiTao]
      ,[sTen]
      ,[sType]
      ,[Tag]) values ('MIGRATE_EXCEPT', 2022, 999, 1, NULL, NULL, 2023, N'Không migrate dữ liệu của năm', 'Admin', 'Admin', 'Migrate Except', 'DM_CauHinh', NULL)
  
  insert DanhMuc ([iID_MaDanhMuc]
      ,[iNamLamViec]
      ,[iThuTu]
      ,[iTrangThai]
      ,[Log]
      ,[NganSachNganh]
      ,[sGiaTri]
      ,[sMoTa]
      ,[sNguoiSua]
      ,[sNguoiTao]
      ,[sTen]
      ,[sType]
      ,[Tag]) values ('MIGRATE_EXCEPT', 2024, 999, 1, NULL, NULL, 2023, N'Không migrate dữ liệu của năm', 'Admin', 'Admin', 'Migrate Except', 'DM_CauHinh', NULL)