--9010011 - Chi kinh phí quản lý BHXH, BHYT (giao chi tiết cho đơn vị)
--9010011-010 - Chi quản lý BHXH, BHYT
--9010011-010-0001 - Ngành Cán bộ
--9010011-010-0002 - Ngành Quân lực
--9010011-010-0003 - Ngành Tài chính
--9010011-010-0004 - Ngành Quân y
--9010011-011 - Hỗ trợ cán bộ chuyên trách làm công tác BHXH, BHYT
--9010011-012 - Chi tập huấn nghiệp vụ BHXH, BHYT, BHTN
--9010011-013 - Hỗ trợ quản lý thu, chi BHXH, BHYT ở đơn vị cơ sở
--9010011-013-0001 - Chi thường xuyên đặc thù
--9010011-013-0001-0001 - Ngành Cán bộ
--9010011-013-0001-0002 - Ngành Quân lực
--9010011-013-0001-0003 - Ngành Tài chính
--9010011-013-0001-0004 - Ngành Quân y
--9010011-013-0002 - Chi không thường xuyên

--2023
GO
DELETE FROM BH_DM_MucLucNganSach WHERE sxaunoima in ('9010011','9010011-010','9010011-010-0001','9010011-010-0002','9010011-010-0003','9010011-010-0004','9010011-011','9010011-012','9010011-013','9010011-013-0001','9010011-013-0001-0001','9010011-013-0001-0002','9010011-013-0001-0003','9010011-013-0001-0004','9010011-013-0002')
	AND iNamLamViec = 2023
GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', NULL, NULL, N'9010011', NULL, NULL, N'Chi kinh phí quản lý BHXH, BHYT (giao chi tiết cho đơn vị)', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', NULL, N'010', N'9010011', NULL, NULL, N'Chi quản lý BHXH, BHYT', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0001', N'010', N'9010011', NULL, NULL, N'- Ngành Cán bộ', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0001', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0002', N'010', N'9010011', NULL, NULL, N'- Ngành Quân lực', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0002', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0003', N'010', N'9010011', NULL, NULL, N'- Ngành Tài chính', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0003', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0004', N'010', N'9010011', NULL, NULL, N'- Ngành Quân y', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0004', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', NULL, N'011', N'9010011', NULL, NULL, N'Hỗ trợ cán bộ chuyên trách làm công tác BHXH, BHYT', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-011', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', NULL, N'012', N'9010011', NULL, NULL, N'Chi tập huấn nghiệp vụ BHXH, BHYT, BHTN', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-012', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', NULL, N'013', N'9010011', NULL, NULL, N'Hỗ trợ quản lý thu, chi BHXH, BHYT ở đơn vị cơ sở', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', NULL, NULL, N'Chi thường xuyên đặc thù', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0001', NULL, N'- Ngành Cán bộ', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0001', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0002', NULL, N'- Ngành Quân lực', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0002', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0003', NULL, N'- Ngành Tài chính', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0003', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0004', NULL, N'- Ngành Quân y', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0004', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2023-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2023-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013' and iNamLamViec = 2023)
, NULL, NULL, N'STM', NULL, 0, 2023, 1, NULL, NULL, N'NG', N'', N'0002', N'013', N'9010011', NULL, NULL, N'Chi không thường xuyên', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0002', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

--2024
GO
DELETE FROM BH_DM_MucLucNganSach WHERE sxaunoima in ('9010011','9010011-010','9010011-010-0001','9010011-010-0002','9010011-010-0003','9010011-010-0004','9010011-011','9010011-012','9010011-013','9010011-013-0001','9010011-013-0001-0001','9010011-013-0001-0002','9010011-013-0001-0003','9010011-013-0001-0004','9010011-013-0002')
	AND iNamLamViec = 2024
GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', NULL, NULL, N'9010011', NULL, NULL, N'Chi kinh phí quản lý BHXH, BHYT (giao chi tiết cho đơn vị)', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', NULL, N'010', N'9010011', NULL, NULL, N'Chi quản lý BHXH, BHYT', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0001', N'010', N'9010011', NULL, NULL, N'- Ngành Cán bộ', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0001', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0002', N'010', N'9010011', NULL, NULL, N'- Ngành Quân lực', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0002', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0003', N'010', N'9010011', NULL, NULL, N'- Ngành Tài chính', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0003', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0004', N'010', N'9010011', NULL, NULL, N'- Ngành Quân y', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0004', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', NULL, N'011', N'9010011', NULL, NULL, N'Hỗ trợ cán bộ chuyên trách làm công tác BHXH, BHYT', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-011', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', NULL, N'012', N'9010011', NULL, NULL, N'Chi tập huấn nghiệp vụ BHXH, BHYT, BHTN', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-012', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', NULL, N'013', N'9010011', NULL, NULL, N'Hỗ trợ quản lý thu, chi BHXH, BHYT ở đơn vị cơ sở', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', NULL, NULL, N'Chi thường xuyên đặc thù', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0001', NULL, N'- Ngành Cán bộ', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0001', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0002', NULL, N'- Ngành Quân lực', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0002', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0003', NULL, N'- Ngành Tài chính', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0003', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0004', NULL, N'- Ngành Quân y', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0004', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2024-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2024-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013' and iNamLamViec = 2024)
, NULL, NULL, N'STM', NULL, 0, 2024, 1, NULL, NULL, N'NG', N'', N'0002', N'013', N'9010011', NULL, NULL, N'Chi không thường xuyên', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0002', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

--2025
GO
DELETE FROM BH_DM_MucLucNganSach WHERE sxaunoima in ('9010011','9010011-010','9010011-010-0001','9010011-010-0002','9010011-010-0003','9010011-010-0004','9010011-011','9010011-012','9010011-013','9010011-013-0001','9010011-013-0001-0001','9010011-013-0001-0002','9010011-013-0001-0003','9010011-013-0001-0004','9010011-013-0002')
	AND iNamLamViec = 2025
GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', NULL, NULL, N'9010011', NULL, NULL, N'Chi kinh phí quản lý BHXH, BHYT (giao chi tiết cho đơn vị)', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', NULL, N'010', N'9010011', NULL, NULL, N'Chi quản lý BHXH, BHYT', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0001', N'010', N'9010011', NULL, NULL, N'- Ngành Cán bộ', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0001', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0002', N'010', N'9010011', NULL, NULL, N'- Ngành Quân lực', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0002', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0003', N'010', N'9010011', NULL, NULL, N'- Ngành Tài chính', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0003', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-010' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0004', N'010', N'9010011', NULL, NULL, N'- Ngành Quân y', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-010-0004', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', NULL, N'011', N'9010011', NULL, NULL, N'Hỗ trợ cán bộ chuyên trách làm công tác BHXH, BHYT', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-011', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', NULL, N'012', N'9010011', NULL, NULL, N'Chi tập huấn nghiệp vụ BHXH, BHYT, BHTN', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-012', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', NULL, N'013', N'9010011', NULL, NULL, N'Hỗ trợ quản lý thu, chi BHXH, BHYT ở đơn vị cơ sở', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', NULL, NULL, N'Chi thường xuyên đặc thù', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0001', NULL, N'- Ngành Cán bộ', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0001', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0002', NULL, N'- Ngành Quân lực', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0002', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0003', NULL, N'- Ngành Tài chính', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0003', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013-0001' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0001', N'013', N'9010011', N'0004', NULL, N'- Ngành Quân y', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0001-0004', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

GO
INSERT [dbo].[BH_DM_MucLucNganSach] ([iID], [bDuPhong], [bHangCha], [bHangChaDuToan], [bHangChaQuyetToan], [bHangMua], [bHangNhap], [bHienVat], [bNgay], [bPhanCap], [bSoNguoi], [bTonKho], [bTuChi], [dNgaySua], [dNgayTao], [iID_MLNS], [iID_MLNS_Cha], [iID_MaBQuanLy], [iID_MaDonVi], [iLoai], [iLoaiNganSach], [iLock], [iNamLamViec], [iTrangThai], [Log], [sCPChiTietToi], [sChiTietToi], [sDuToanChiTietToi], [sK], [sL], [sLNS], [sM], [sMaCB], [sMoTa], [sNG], [sNguoiSua], [sNguoiTao], [sNhapTheoTruong], [sQuyetToanChiTietToi], [sTM], [sTNG], [sTNG1], [sTNG2], [sTNG3], [sTTM], [Tag], [sXauNoiMa], [sMaPhuCap], [bHangChaDuToanDieuChinh], [sDuToanDieuChinhChiTietToi], [iDonViTinh], [fTyLe_BHTN_NLD], [fTyLe_BHTN_NSD], [fTyLe_BHXH_NLD], [fTyLe_BHXH_NSD], [fTyLe_BHYT_NLD], [fTyLe_BHYT_NSD], [sLuongChinh], [sNS_LuongChinh], [sNS_PCCV], [sNS_PCTN], [sNS_PCTNVK], [sPCCV], [sPCTN], [sPCTNVK], [sNS_HSBL]) 
VALUES (NEWID(), 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, CAST(N'2025-08-26T11:32:29.5989902' AS DateTime2), CAST(N'2025-08-26T11:31:18.8342156' AS DateTime2), NEWID(), 
(select iID_MLNS from BH_DM_MucLucNganSach where sxaunoima = '9010011-013' and iNamLamViec = 2025)
, NULL, NULL, N'STM', NULL, 0, 2025, 1, NULL, NULL, N'NG', N'', N'0002', N'013', N'9010011', NULL, NULL, N'Chi không thường xuyên', N'', N'admin', N'admin', NULL, N'', NULL, N'', N'', N'', N'', N'', NULL, N'9010011-013-0002', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
