using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;
using VTS.QLNS.CTC.App.Model;
using VTS.QLNS.CTC.App.View.SocialInsurance.SocialInsuranceSettlement.QuyetToanCapKinhPhiKCBBHYT.PrintReport;
using VTS.QLNS.CTC.App.ViewModel;
using VTS.QLNS.CTC.App.ViewModel.Budget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Allocation;
using VTS.QLNS.CTC.App.ViewModel.Budget.Allocation.ExportAllocation;
using VTS.QLNS.CTC.App.ViewModel.Budget.Allocation.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.Budget.Allocation.Report;
using VTS.QLNS.CTC.App.ViewModel.Budget.Army;
using VTS.QLNS.CTC.App.ViewModel.Budget.CollectionsBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.CollectionsBudget.BudgetApprobation;
using VTS.QLNS.CTC.App.ViewModel.Budget.CollectionsBudget.Plan;
using VTS.QLNS.CTC.App.ViewModel.Budget.CollectionsBudget.RealRevenueExpenditure;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Check;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Check.ImportCheck;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Check.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Demand;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Demand.ExportDemand;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Demand.SendDataDemand;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Demand3Y;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Distribution;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Distribution.ImportExpertise;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Expertise;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.ExpertiseInternal;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Import;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.LevelBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Plan;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Plan.ExportPlanBeginYear;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.Plan.SendDataPlanBeginYear;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.PlanAgency;
using VTS.QLNS.CTC.App.ViewModel.Budget.DemandCheck.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.Budget.Diagram;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate.AdjustedEstimate;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate.Division;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate.Division.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate.DivisionEstimate;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate.DivisionEstimate.ExportReport;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate.DivisionEstimate.SendDataDivisionEstimate;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate.Hospital;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate.Import;
using VTS.QLNS.CTC.App.ViewModel.Budget.Estimate.Report;
using VTS.QLNS.CTC.App.ViewModel.Budget.MigrationData;
using VTS.QLNS.CTC.App.ViewModel.Budget.Report;
using VTS.QLNS.CTC.App.ViewModel.Budget.RevenueExpenditure.ApprovedEstimation;
using VTS.QLNS.CTC.App.ViewModel.Budget.RevenueExpenditure.Import;
using VTS.QLNS.CTC.App.ViewModel.Budget.RevenueExpenditure.Plan;
using VTS.QLNS.CTC.App.ViewModel.Budget.RevenueExpenditure.Plan.PrintPlanReport;
using VTS.QLNS.CTC.App.ViewModel.Budget.RevenueExpenditure.RealRevenueExpenditure;
using VTS.QLNS.CTC.App.ViewModel.Budget.RevenueExpenditure.RealRevenueExpenditure.PrintRealRevenueExpenditureReport;
using VTS.QLNS.CTC.App.ViewModel.Budget.RevenueExpenditure.RevenueExpenditureDivision;
using VTS.QLNS.CTC.App.ViewModel.Budget.RevenueExpenditure.RevenueExpenditureSettlement;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.DefenseBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.DefenseBudget.ExportDefenseBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.DefenseBudget.SendDataDefenseBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.Diagram;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.ExpenseBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.ExpenseBudget.ExportExpenseBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.ExpenseBudget.SendDataExpenseBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.Explanation;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.ForexBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.ForexBudget.ExportForexBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.ForexBudget.SendDataForexBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.GetDataLuong;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.Import;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.RegularBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.RegularBudget.ExportDemandBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.RegularBudget.SendDataRegularBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.StateBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.StateBudget.ExportStateBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.StateBudget.SendDataStateBudget;
using VTS.QLNS.CTC.App.ViewModel.Budget.Settlement.VoucherList;
using VTS.QLNS.CTC.App.ViewModel.Category;
using VTS.QLNS.CTC.App.ViewModel.Forex;
using VTS.QLNS.CTC.App.ViewModel.Forex.Allocation.ForexDeNghiThanhToan;
using VTS.QLNS.CTC.App.ViewModel.Forex.Allocation.ForexPheDuyetThanhToan;
using VTS.QLNS.CTC.App.ViewModel.Forex.Allocation.ForexThongTriCapPhat;
using VTS.QLNS.CTC.App.ViewModel.Forex.Allocation.ForexTinhHinhThucHienNganSach;
using VTS.QLNS.CTC.App.ViewModel.Forex.Domestic.BaoCaoTinhHinhThucHienDuAn;
using VTS.QLNS.CTC.App.ViewModel.Forex.Domestic.ExchangeRateDifference;
using VTS.QLNS.CTC.App.ViewModel.Forex.Domestic.ExchangeRateDifference.PrintDialog;
using VTS.QLNS.CTC.App.ViewModel.Forex.Domestic.TongHopThongTinDuAn;
using VTS.QLNS.CTC.App.ViewModel.Forex.ExchangeRate;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForeignTrade.ContractorPackage;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexAllocation;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexAllocation.ForexDeNghiThanhToan.PrintDialog;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexAllocation.ForexPheDuyetThanhToan.PrintDialog;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDanhMucNhaThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDanhMucNhaThau.ImportNhaThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.ChiPhiKhac.QuyetDinhChiPhiKhac;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.ChuanBiDauTu.DACBDTForexProjectInformation;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.ChuanBiDauTu.DACBDTForexProjectInformation.DACBDTImportThongTinDuAn;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.ChuanBiDauTu.DACBDTInvestmentDecision;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.ChuanBiDauTu.DACBDTInvestmentPolicy;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.QuanLyDuAn.ForexDomesticBiddingPackagel;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.QuanLyDuAn.NHHopDongTrongNuoc;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.QuanLyDuAn.NHHopDongTrongNuoc.ImportHopDong;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.QuanLyDuAn.NHKeHoachLuaChonNhaThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.QuanLyDuAn.NHKeHoachLuaChonNhaThau.ImportGoiThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.QuanLyDuAn.ThietKeKyThuatTongDuToan;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.QuanLyHopDongNhapKhau.DAHDNKDecision;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexDuAn.QuanLyHopDongNhapKhau.DAPlanImport;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexKhoiTaoCapPhat;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexKhoiTaoCapPhat.ForexDanhSachKhoiTao;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexKhoiTaoCapPhat.KhoiTaoTheoQuyetDinh;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.ChiPhiKhac.QuyetDinhChiPhiKhac;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.ChuanBiDauTu.MSCBDTForexProjectInformation;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.ChuanBiDauTu.MSCBDTForexProjectInformation.MSCBDTImportThongTinDuAn;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.ChuanBiDauTu.MSCBDTInvestmentDecision;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.ChuanBiDauTu.MSCBDTInvestmentPolicy;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTDecision;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTGoiThauTrongNuoc;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTKeHoachLuaChonNhaThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTKeHoachLuaChonNhaThau.MSNTImportGoiThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTNHHopDongTrongNuoc;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTNHHopDongTrongNuoc.MSNTImportHopDong;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTPlanImport;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTThietKeKyThuatTongDuToan;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamTrongNuoc.MSTNGoiThauTrongNuoc;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamTrongNuoc.MSTNHopDongTrongNuocKhongGoiThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamTrongNuoc.MSTNHopDongTrongNuocKhongGoiThau.MSTNImportHopDongKhongGoiThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamTrongNuoc.MSTNImportHopDong;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamTrongNuoc.MSTNKeHoachDatHang;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamTrongNuoc.MSTNKeHoachLuaChonNhaThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamTrongNuoc.MSTNKeHoachLuaChonNhaThau.MSTNImportGoiThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamTrongNuoc.MSTNNHHopDongTrongNuoc;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.MuaSamTrongNuoc.MSTNThietKeKyThuatTongDuToan;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiNgoaiThuong.MSCNTForexContractInfo;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiNgoaiThuong.MSCNTForexContractInfo.MSCNTImportHopDongNgoaiThuong;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiNgoaiThuong.MSPCNTDecision;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiNgoaiThuong.MSPlanImport;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiTrongNuoc.MSCTNGoiThauTrongNuoc;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiTrongNuoc.MSCTNKeHoachLuaChonNhaThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiTrongNuoc.MSCTNKeHoachLuaChonNhaThau.MSCTNImportGoiThau;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiTrongNuoc.MSCTNNHHopDongTrongNuoc;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiTrongNuoc.MSCTNNHHopDongTrongNuoc.MSCTNImportHopDong;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexMuaSam.PhanChiTrongNuoc.MSCTNThietKeKyThuatTongDuToan;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexPlan;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexPlan.NhuCauChiQuy;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexPlan.PlanDetail;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexPlan.PlanOverview;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexSettlement;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexSettlement.BaoCaoQuyetToan;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexSettlement.ChuyenDuLieuQuyetToan;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexSettlement.DeNghiQTDAHT;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexSettlement.ForexAsset;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexSettlement.PheDuyetQuyetToanDAHT;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexSettlement.QuyetToanNienDo;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexSettlement.QuyetToanNienDo.PrintDialog;
using VTS.QLNS.CTC.App.ViewModel.Forex.ForexSettlement.ThongTriQuyetToan;
using VTS.QLNS.CTC.App.ViewModel.Investment;
using VTS.QLNS.CTC.App.ViewModel.Investment.EndOfInvestment;
using VTS.QLNS.CTC.App.ViewModel.Investment.EndOfInvestment.AnnualSettlement;
using VTS.QLNS.CTC.App.ViewModel.Investment.EndOfInvestment.ApproveSettlementDone;
using VTS.QLNS.CTC.App.ViewModel.Investment.EndOfInvestment.QuyetToanVDT;
using VTS.QLNS.CTC.App.ViewModel.Investment.EndOfInvestment.QuyetToanVDT.PrintDialog;
using VTS.QLNS.CTC.App.ViewModel.Investment.EndOfInvestment.RequestSettlement;
using VTS.QLNS.CTC.App.ViewModel.Investment.EndOfInvestment.ThongTriQuyetToan;
using VTS.QLNS.CTC.App.ViewModel.Investment.Initialization;
using VTS.QLNS.CTC.App.ViewModel.Investment.Initialization.InitializationProcess;
using VTS.QLNS.CTC.App.ViewModel.Investment.Initialization.InitializationProject;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.ApprovalOfAdvanceCaptital;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.BaoCaoKetQuaGiaiNganChiKPDT;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.CapPhatThanhToan;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.CapPhatThanhToan.PrintDialog;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.DeNghiThanhToanChiPhi;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.PheDuyetThanhToan;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.PheDuyetThanhToan.PrintDialog;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.PrintReportAnnualBudgetAllocation;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.PrintReportProcessProject;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.ThanhToanKhoBac;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.ThongTriCapPhat;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentImplementation.ThongTriCapPhat.PrintDialog;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.AdvanceCapitalApproved;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.KeHoachChiQuy;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.KeHoachChiQuy.PrintDialog;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.KeHoachVonNamDuocDuyet;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.KeHoachVonUngDeXuat;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.PrintReportAdjustmentPlan;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.VonNamDonVi;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.YearPlan;
using VTS.QLNS.CTC.App.ViewModel.Investment.InvestmentStandard.YearPlanImport;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.ChuTruongDauTu;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.ContractInfo;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.GiaoDuToanChiPhi;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.GoiThau;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.KHLuaChonNhaThau;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.PheDuyetDuAn;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.PlanManager;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.PlanManagerApproved;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.PlanSuggestions;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.QLDuAn;
using VTS.QLNS.CTC.App.ViewModel.Investment.MediumTermPlan.TKTCVaTongDuToan;
using VTS.QLNS.CTC.App.ViewModel.MediumTermPlan.PheDuyetDuAn;
using VTS.QLNS.CTC.App.ViewModel.Salary;
using VTS.QLNS.CTC.App.ViewModel.Salary.Cadres;
using VTS.QLNS.CTC.App.ViewModel.Salary.Cadres.CadresBHXH;
using VTS.QLNS.CTC.App.ViewModel.Salary.Cadres.IncomeTax;
using VTS.QLNS.CTC.App.ViewModel.Salary.Cadres.LaunchAdjusted;
using VTS.QLNS.CTC.App.ViewModel.Salary.ImportSalary;
using VTS.QLNS.CTC.App.ViewModel.Salary.Report;
using VTS.QLNS.CTC.App.ViewModel.Salary.Report.ListReport;
using VTS.QLNS.CTC.App.ViewModel.Salary.Report.ReportSalaryPursuit;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.BackPaySalaryMonthTable;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.CalculateSalary;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.CalculateSalary.ImportCongThuc;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.CategoryHoliday;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.InsuranceSalaryMonthTable;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.InsuranceSalaryMonthTable.Export;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.PursuitSalaryMonthTable;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.SalaryComparison;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.SalaryDevelopments;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagement.SalaryTableMonth;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagementPlan;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagementPlan.AllowenceAdjustment;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagementPlan.CadresPlan;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagementPlan.CBNHKeHoach;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagementPlan.ConfigurationUpRank;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagementPlan.MilitaryAdjustment;
using VTS.QLNS.CTC.App.ViewModel.Salary.SalaryManagementPlan.SalaryYearPlan;
using VTS.QLNS.CTC.App.ViewModel.Salary.Settlement;
using VTS.QLNS.CTC.App.ViewModel.Salary.Settlement.FeeCollectionManagement;
using VTS.QLNS.CTC.App.ViewModel.Salary.Settlement.RegularSettlement;
using VTS.QLNS.CTC.App.ViewModel.Salary.Settlement.SalaryConfiguration;
using VTS.QLNS.CTC.App.ViewModel.Salary.Settlement.SettlementNumber;
using VTS.QLNS.CTC.App.ViewModel.Salary.TransferData;
using VTS.QLNS.CTC.App.ViewModel.Salary.TransferData.AllowenceMapper;
using VTS.QLNS.CTC.App.ViewModel.Salary.TransferData.ColumnMapper;
using VTS.QLNS.CTC.App.ViewModel.Salary.TransferData.TransferCadres;
using VTS.QLNS.CTC.App.ViewModel.Salary.TransferData.TransferDataKtdt;
using VTS.QLNS.CTC.App.ViewModel.Setting;
using VTS.QLNS.CTC.App.ViewModel.Shared;
using VTS.QLNS.CTC.App.ViewModel.Shared.ImportViewModel;
using VTS.QLNS.CTC.App.ViewModel.Shared.Settings;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.Estimate;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.Report;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.CapPhatBoSung;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.CapPhatBoSung.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.CapPhatBoSung.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.CapPhatTamUngBHYT.ExportReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.CapPhatTamUngBHYT.ImportCptuBHYT;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.ChungTuCapPhat;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.ChungTuCapPhat.ImportChungTuCapPhat;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.ChungTuCapPhat.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceAllocation.Report;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.DieuChinhDuToanBHXH;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.DieuChinhDuToanBHXH.ImportDieuChinhDuToan;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.DieuChinhDuToanBHXH.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.DieuChinhDuToanThu;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.DieuChinhDuToanThu.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.DieuChinhDuToanThu.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.DuToanThuBHXH;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.DuToanThuBHXH.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.NhanDuToanChiTrenGiao;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.NhanDuToanChiTrenGiao.ImportNdtBHXH;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.NhanDuToanChiTrenGiao.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.NhanPhanBoDuToanThuBHYT;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.NhanPhanBoDuToanThuBHYT.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.PhanBoDuToanChi;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.PhanBoDuToanChi.ExportReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.PhanBoDuToanChi.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.PhanBoDuToanThu;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.PhanBoDuToanThu.ExportReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.PhanBoDuToanThuMuaBHYT;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.PhanBoDuToanThuMuaBHYT.ExportReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceEstimate.Report;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.KeHoachThu;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.KeHoachThu.ImportKhtBHXH;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.KeHoachThu.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.KeHoachThuMuaBHYT;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.KeHoachThuMuaBHYT.ImportKhtmBHYT;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.KeHoachThuMuaBHYT.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChi;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChi.ImportKhcBHXH;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChi.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChiKCBQYDV;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChiKCBQYDV.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChiKCBQYDV.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChiKhac;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChiKhac.ImportKhcK;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChiKhac.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChiQuanLy;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChiQuanLy.ImportKhcQuanLyKinhPhi;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsurancePlan.LapKeHoachChiQuanLy.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanCapKinhPhiKCBBHYT;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanCapKinhPhiKCBBHYT.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiKinhPhiQuanLy;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiKinhPhiQuanLy.Explanation;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiKinhPhiQuanLy.ImportChiKinhPhiQuanLy;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiKinhPhiQuanLy.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiNamBHXH;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiNamBHXH.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiNamBHXH.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiNamBHXH.PritnReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiNamKCB;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiNamKCB.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiNamKCB.PritnReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyBHXH;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyBHXH.Explanation;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyBHXH.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyBHXH.ImportExplanation;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyBHXH.PritnReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyKCB;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyKCB.Explanation;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyKCB.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyKCB.PritnReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyKinhPhiKhac;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyKinhPhiKhac.Explanation;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyKinhPhiKhac.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanChiQuyKinhPhiKhac.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanNamChiKinhPhiKhac;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanNamChiKinhPhiKhac.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanNamChiKinhPhiKhac.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanNamChiKinhPhiQuanLy;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanNamChiKinhPhiQuanLy.Import;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanNamChiKinhPhiQuanLy.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanThuBHXH;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanThuBHXH.Explanation;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanThuBHXH.ImportExcel;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanThuBHXH.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanThuMuaBHYT;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanThuMuaBHYT.ImportExcel;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.QuyetToanThuMuaBHYT.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.Report;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.ThamDinhQuyetToan;
using VTS.QLNS.CTC.App.ViewModel.SocialInsurance.SocialInsuranceSettlement.ThamDinhQuyetToan.PrintReport;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.AppVersion;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.BackupRestore;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.BackupRestore.BackupAndRestore;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.BackupRestore.File;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.BackupRestore.Schedule;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.SysLog;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.UserManagement;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.UserManagement.Group;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.UserManagement.User;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.Utilities;
using VTS.QLNS.CTC.App.ViewModel.SystemAdmin.Utilities.Tool;

namespace VTS.QLNS.CTC.App.DIConfigure
{
    public static class AddViewModelsDIConfigureExtensions
    {
        public static IServiceCollection AddViewModels(this IServiceCollection services)
        {
            services.AddTransient<LoginViewModel>();
            services.AddTransient<MainWindowViewModel>();
            services.AddTransient<HomeViewModel>();
            services.AddTransient<SystemAdminViewModel>();
            services.AddTransient<CategoryViewModel>();
            services.AddTransient<BudgetViewModel>();
            services.AddTransient<InvestmentViewModel>();
            services.AddTransient<SocialInsuranceViewModel>();
            services.AddTransient<ForexViewModel>();
            services.AddTransient<SalaryViewModel>();
            services.AddTransient<ColorToolViewModel>();
            services.AddTransient<DiagramViewModel>();
            services.AddTransient<DemandCheckViewModel>();
            services.AddTransient<EstimateViewModel>();
            services.AddTransient<SettlementViewModel>();
            services.AddTransient<AllocationViewModel>();
            services.AddTransient<DivisionIndexViewModel>();
            services.AddTransient<DivisionImportJsonViewModel>();
            services.AddTransient<DivisionEstimateImportJsonViewModel>();
            services.AddTransient<DivisionEstimateIndexViewModel>();
            services.AddTransient<ExportDivisionEstimateViewModel>();
            services.AddTransient<ExportJsonDivisionEstimateViewModel>();
            services.AddTransient<SendDataDivisionEstimateViewModel>();
            services.AddTransient<ReportDivisionCurrentViewModel>();
            services.AddTransient<DivisionDialogViewModel>();
            services.AddTransient<AllocationDialogViewModel>();
            services.AddTransient<DivisionEstimateDialogViewModel>();
            services.AddTransient<DivisionDetailViewModel>();
            services.AddTransient<DivisionEstimateDetailViewModel>();
            services.AddTransient<ReportDivisionCurrentDialogViewModel>();
            services.AddTransient<ReportDivisionCurrentBatchDialogViewModel>();
            services.AddTransient<DivisionDetailCanCuViewModel>();
            services.AddTransient<SettlementDiagramViewModel>();
            services.AddTransient<RegularBudgetIndexViewModel>();
            services.AddTransient<ExportRegularBudgetViewModel>();
            services.AddTransient<SendDataRegularBudgetViewModel>();
            services.AddTransient<DefenseBudgetIndexViewModel>();
            services.AddTransient<ExportDefenseBudgetViewModel>();
            services.AddTransient<SendDataDefenseBudgetViewModel>();
            services.AddTransient<StateBudgetIndexViewModel>();
            services.AddTransient<ExportStateBudgetViewModel>();
            services.AddTransient<SendDataStateBudgetViewModel>();
            services.AddTransient<AllocationIndexViewModel>();
            services.AddTransient<ExportAllocationViewModel>();
            services.AddTransient<AllocationDiagramViewModel>();
            services.AddTransient<AllocationReportViewModel>();
            services.AddTransient<AllocationDetailViewModel>();
            services.AddTransient<DemandCheckFunctionMapViewModel>();
            services.AddTransient<DemandIndexViewModel>();
            services.AddTransient<Demand3YIndexViewModel>();
            services.AddTransient<SendDataDemandViewModel>();
            services.AddTransient<DemandDialogViewModel>();
            services.AddTransient<Demand3YDialogViewModel>();
            services.AddTransient<DemandDetailViewModel>();
            services.AddTransient<Demand3YDetailViewModel>();
            services.AddTransient<CheckIndexViewModel>();
            services.AddTransient<CheckDialogViewModel>();
            services.AddTransient<CheckDetailViewModel>();
            services.AddTransient<DistributionIndexViewModel>();
            services.AddTransient<SendDataDistributionViewModel>();
            services.AddTransient<DistributionImportJsonViewModel>();
            services.AddTransient<DistributionDialogViewModel>();
            services.AddTransient<DistributionDetailViewModel>();
            services.AddTransient<DistributionChildDetailViewModel>();
            services.AddTransient<RegularBudgetDialogViewModel>();
            services.AddTransient<RegularBudgetDetailViewModel>();
            services.AddTransient<DefenseBudgetDialogViewModel>();
            services.AddTransient<DefenseBudgetDetailViewModel>();
            services.AddTransient<StateBudgetDialogViewModel>();
            services.AddTransient<StateBudgetDetailViewModel>();
            services.AddTransient<UserManagementViewModel>();
            services.AddTransient<UserIndexViewModel>();
            services.AddTransient<UserDialogViewModel>();
            services.AddTransient<GroupIndexViewModel>();
            services.AddTransient<GroupDialogViewModel>();
            services.AddTransient<PrintAllocationNoticeViewModel>();
            services.AddTransient<AllocationReportCompareViewModel>();
            services.AddTransient<AllocationReportUnitsCompareViewModel>();
            services.AddTransient<DataInterpretationViewModel>();
            services.AddTransient<VerbalExplanationViewModel>();
            services.AddTransient<ArmyIndexViewModel>();
            services.AddTransient<ArmyDialogViewModel>();
            services.AddTransient<ArmyDetailViewModel>();
            services.AddTransient<PlanBeginYearIndexViewModel>();
            services.AddTransient<ExportPlanBeginYearViewModel>();
            services.AddTransient<SendDataPlanBeginYearViewModel>();
            services.AddTransient<PlanBeginYearDetailViewModel>();
            services.AddTransient<PlanBeginYearImportJsonViewModel>();
            services.AddTransient<InvestmentImplementationViewModel>();
            services.AddTransient<AdvanceCapitalApprovedIndexViewModel>();
            services.AddTransient<AdvanceCapitalApprovedDialogViewModel>();
            services.AddTransient<AdvanceCapitalApprovedDetailViewModel>();
            services.AddTransient<EndOfInvestmentViewModel>();
            services.AddTransient<AnnualSettlementIndexViewModel>();
            services.AddTransient<AnnualSettlementDialogViewModel>();
            services.AddTransient<AnnualSettlementDetailViewModel>();
            services.AddTransient<ApprovalOfAdvanceCaptitalIndexViewModel>();
            services.AddTransient<ApprovalOfAdvanceCaptitalDialogViewModel>();
            services.AddTransient<ApprovalOfAdvanceCaptitalDetailViewModel>();
            services.AddTransient<YearPlanUnitIndexViewModel>();
            services.AddTransient<YearPlanUnitDialogViewModel>();
            services.AddTransient<YearPlanUnitDetailViewModel>();
            services.AddTransient<ThongTriCapPhatIndexViewModel>();
            services.AddTransient<ThongTriCapPhatDialogViewModel>();
            services.AddTransient<ThongTriCapPhatDetailViewModel>();
            services.AddTransient<ViewModel.Investment.EndOfInvestment.ThongTriQuyetToan.ThongTriQuyetToanIndexViewModel>();
            services.AddTransient<ViewModel.Investment.EndOfInvestment.ThongTriQuyetToan.ThongTriQuyetToanDialogViewModel>();
            services.AddTransient<ThongTriQuyetToanDetailViewModel>();
            services.AddTransient<ProjectInPlanManagerApprovedDiaLogViewModel>();
            services.AddTransient<YearPlanImportViewModel>();
            services.AddTransient<CadresViewModel>();
            services.AddTransient<CadresIndexViewModel>();
            services.AddTransient<CadresDialogViewModel>();
            services.AddTransient<SalaryManagementViewModel>();
            services.AddTransient<CalculateSalaryIndexViewModel>();
            services.AddTransient<CalculateSalaryDialogViewModel>();
            services.AddTransient<PursuitSalaryIndexViewModel>();
            services.AddTransient<PursuitSalaryDialogViewModel>();
            services.AddTransient<SalaryTableMonthIndexViewModel>();
            services.AddTransient<SalaryTableMonthDialogViewModel>();
            services.AddTransient<PursuitSalaryDetailViewModel>();
            services.AddTransient<YearPlanUnitImportViewModel>();
            services.AddTransient<SalaryTableMonthIndexViewModel>();
            services.AddTransient<FeeCollectionManagementBhxhIndexViewModel>();
            services.AddTransient<FeeCollectionManagementBhxhDialogViewModel>();
            services.AddTransient<FeeCollectionManagementBhxhDetailViewModel>();
            services.AddTransient<FeeCollectionManagementBhxhAggregateDialogViewModel>();
            services.AddTransient<ImportFeeCollectionBhxhViewModel>();
            services.AddTransient<PlanSuggestionsImportViewModel>();
            services.AddTransient<KHLuaChonNhaThauIndexViewModel>();
            services.AddTransient<KHLuaChonNhaThauDialogViewModel>();
            services.AddTransient<KHLuaChonNhaThauDetailViewModel>();
            services.AddTransient<InsuranceSalaryAddDialogViewModel>();
            services.AddTransient<BackPaySalaryAddDialogViewModel>();
            services.AddTransient<InsuranceSalaryDetailViewModel>();
            services.AddTransient<BackPaySalaryDetailViewModel>();
            services.AddTransient<PheDuyetDuAnIndexViewModel>();
            services.AddTransient<PheDuyetDuAnDialogViewModel>();
            services.AddTransient<PheDuyetDuAnDetailViewModel>();
            services.AddTransient<PheDuyetDuAnDieuChinhDetailViewModel>();
            services.AddTransient<PheDuyetDuAnDieuChinhDialogViewModel>();
            services.AddTransient<PheDuyetDuAnHangMucAllDeTailViewModel>();
            services.AddTransient<CadresFinanceReferralViewModel>();
            services.AddTransient<SalarySettlementViewModel>();
            services.AddTransient<SettlementImportJsonViewModel>();
            services.AddTransient<SalaryConfigurationIndexViewModel>();
            services.AddTransient<RegularSettlementIndexViewModel>();
            services.AddTransient<QuyetToanVDTIndexViewModel>();
            services.AddTransient<QuyetToanVDTDialogViewModel>();
            services.AddTransient<QuyetToanVDTDetailViewModel>();
            services.AddTransient<QuyetToanVDTPrintReportViewModel>();
            services.AddTransient<RegularSettlementDialogViewModel>();
            services.AddTransient<RegularSettlementDetailViewModel>();
            services.AddTransient<QuyetToanVDTIndexViewModel>();
            services.AddTransient<QuyetToanVDTDialogViewModel>();
            services.AddTransient<QuyetToanVDTDetailViewModel>();
            services.AddTransient<SalaryManagementPlanViewModel>();
            services.AddTransient<AllowenceAdjustmentIndexViewModel>();
            services.AddTransient<CadresPlanIndexViewModel>();
            services.AddTransient<CBNHKeHoachViewModel>();
            services.AddTransient<CadresCopyMonthDialogViewModel>();
            services.AddTransient<CopyCanBoThangDialogViewModel>();
            services.AddTransient<QuyetToanVDTVonUngDetailViewModel>();
            services.AddTransient<CadresPlanDetailViewModel>();
            services.AddTransient<SalaryYearPlanIndexViewModel>();
            services.AddTransient<SalaryYearPlanDialogViewModel>();
            services.AddTransient<SalaryYearPlanDetailViewModel>();
            services.AddTransient<CadresUpdateMultiAllowenceViewModel>();
            services.AddTransient<DeleteCadresPlanDialogViewModel>();
            services.AddTransient<TransferDataViewModel>();
            services.AddTransient<TransferDataIndexViewModel>();
            services.AddTransient<TransferDataDialogViewModel>();
            services.AddTransient<AllowenceMapperIndexViewModel>();
            services.AddTransient<ColumnMapperIndexViewModel>();
            services.AddTransient<KeHoachVonUngDeXuatIndexViewModel>();
            services.AddTransient<KeHoachVonUngDeXuatDialogViewModel>();
            services.AddTransient<KeHoachVonUngDeXuatDetailViewModel>();
            services.AddTransient<KeHoachVonUngDeXuatImportViewModel>();
            services.AddTransient<QuyetToanVDTImportViewModel>();
            services.AddTransient<QuyetToanVDTVonUngImportViewModel>();
            services.AddTransient<TransferDataDetailViewModel>();
            services.AddTransient<TransferDataKtdtIndexViewModel>();
            services.AddTransient<TransferDataKtdtDialogViewModel>();
            services.AddTransient<CadresAdvancedSearchViewModel>();
            services.AddTransient<SalaryYearPlanVolatilityViewModel>();
            services.AddTransient<SalaryTableMonthAggregateDialogViewModel>();
            services.AddTransient<SalaryDevelopmentsIndexViewModel>();
            services.AddTransient<RegularGetEstimatesDialogViewModel>();
            services.AddTransient<RegularSettlementImportViewModel>();
            services.AddTransient<InitializationProcessContractDetailViewModel>();
            services.AddTransient<CategoryForexDialogViewModel>();
            services.AddTransient<SalaryDevelopmentsPrintDialogViewModel>();
            services.AddTransient<CadresLauncAdjustedIndexViewModel>();

            // Print report
            services.AddTransient<PrintEstimateSettlementViewModel>();
            services.AddTransient<DuToanDonViIndexViewModel>();
            services.AddTransient<PrintReportDemandOrgViewModel>();
            services.AddTransient<PrintSummaryRegularSettlementViewModel>();
            services.AddTransient<PrintSettlementVoucherViewModel>();
            services.AddTransient<PrintCommunicateSettlementLNSViewModel>();
            services.AddTransient<PrintCommunicateSettlementAgencyViewModel>();
            services.AddTransient<PrintSummaryDefenseSettlementViewModel>();
            services.AddTransient<PrintSummaryStateSettlementViewModel>();
            services.AddTransient<PrintArmyViewModel>();
            services.AddTransient<PrintArmyUpDownViewModel>();
            services.AddTransient<PrintArmyAverageViewModel>();
            services.AddTransient<PrintArmyRegularViewModel>();
            services.AddTransient<PrintArmyLeaveViewModel>();
            services.AddTransient<PrintArmyJurisprudenceViewModel>();
            services.AddTransient<PrintSummaryYearSettlementViewModel>();
            services.AddTransient<PrintReportPublicSettlementViewModel>();
            services.AddTransient<PrintReportSumaryCheckNumberViewModel>();

            services.AddTransient<CategoryGeneralViewModel>();
            services.AddTransient<CategoryBudgetViewModel>();
            services.AddTransient<CategoryBudgetSourceViewModel>();
            services.AddTransient<CategorySocialInsuranceViewModel>();
            services.AddTransient<CategoryForexViewModel>();
            services.AddTransient<CategoryInvestmentViewModel>();
            services.AddTransient<PrintReportReceiveDivisionViewModel>();
            services.AddTransient<PrintReportGeneralReceiveDivisionViewModel>();
            services.AddTransient<PrintReportPublicDivisionViewModel>();
            services.AddTransient<PrintReportReceiveTheCheckNumberViewModel>();
            services.AddTransient<EstimateDiagramViewModel>();
            services.AddTransient<CategoryPublicFinanceViewModel>();

            services.AddTransient<RevenueExpenditureViewModel>();
            services.AddTransient<PlanBudgetBeginYearIndexViewModel>();
            services.AddTransient<PlanBudgetBeginYearSummaryViewModel>();
            services.AddTransient<PlanBudgetBeginYearReportSummaryViewModel>();
            services.AddTransient<PlanBudgetBeginYearReportViewModel>();

            services.AddTransient<ApprovedEstimationIndexViewModel>();
            services.AddTransient<RealRevenueExpenditureIndexViewModel>();
            services.AddTransient<RevenueExpenditureDivisionIndexViewModel>();
            services.AddTransient<ApprovedEstimationDialogViewModel>();
            services.AddTransient<RevenueExpenditureDivisionDialogViewModel>();
            services.AddTransient<ApprovedEstimationDetailViewModel>();
            services.AddTransient<RealRevenueExpenditureDialogViewModel>();
            services.AddTransient<RevenueExpenditureDivisionDetailViewModel>();
            services.AddTransient<RealRevenueExpenditureDetailViewModel>();
            services.AddTransient<PlanBudgetBeginYearDialogViewModel>();
            services.AddTransient<PlanBudgetBeginYearDetailViewModel>();
            services.AddTransient<PrintRealRevenueExpenditureReportViewModel>();
            services.AddTransient<PrintPlanBudgetReportViewModel>();
            services.AddTransient<PlanBudgetBeginYearImportViewModel>();
            services.AddTransient<RevenueExpenditureImportViewModel>();
            services.AddTransient<RevenueExpenditureDivisionReportViewModel>();

            services.AddTransient<PrintAllocationDonViViewModel>();
            services.AddTransient<PrintAllocationRequestViewModel>();
            services.AddTransient<InvestmentStandardViewModel>();
            services.AddTransient<YearPlanIndexViewModel>();
            services.AddTransient<PrintAllocationDonViViewModel>();
            services.AddTransient<PrintAllocationRequestViewModel>();
            services.AddTransient<YearPlanDialogViewModel>();
            services.AddTransient<YearPlanDialogViewModel>();
            services.AddTransient<YearPlanDetailViewModel>();
            services.AddTransient<SettlementImportViewModel>();
            services.AddTransient<PrintReportChiTietDuToanDonViViewModel>();
            services.AddTransient<PrintReportTongHopDuToanViewModel>();
            services.AddTransient<ImportPlanBeginYearViewModel>();
            services.AddTransient<ImportDemandViewModel>();
            services.AddTransient<ExportDemandViewModel>();
            services.AddTransient<ImportCheckViewModel>();
            services.AddTransient<ImportCheckDetailViewModel>();
            services.AddTransient<PrintReportCoverSheetViewModel>();
            services.AddTransient<PrintReportTargetAgencyViewModel>();
            services.AddTransient<PrintReportTargetAgencyHD4554ViewModel>();
            services.AddTransient<SocialInsuranceDivisionEstimatePrintSheetViewModel>();
            services.AddTransient<PrintReportTargetMajorsViewModel>();
            services.AddTransient<PrintReportTargetMajorsDayViewModel>();
            services.AddTransient<PrintReportSynthesisAgencyViewModel>();
            services.AddTransient<PrintReportSynthesisDivisionViewModel>();
            services.AddTransient<PrintReportTargetAgencyLnsViewModel>();
            services.AddTransient<PrintReportSynthesisTargetMajorsViewModel>();
            services.AddTransient<PrintReportDetailTargetAgencyLnsViewModel>();
            services.AddTransient<DivisionImportViewModel>();
            services.AddTransient<RequestSettlementIndexViewModel>();
            services.AddTransient<RequestSettlementDialogViewModel>();
            services.AddTransient<ProjectInformationPrintReportViewModel>();
            services.AddTransient<ProjectAllocationPrintReportViewModel>();
            services.AddTransient<QLDuAnIndexViewModel>();
            services.AddTransient<QLDuAnDialogViewModel>();
            services.AddTransient<QLDuAnImportViewModel>();
            services.AddTransient<QLDADetailViewModel>();
            services.AddTransient<YearPlanUnitReportViewModel>();
            services.AddTransient<PrintReportPublicFinanceViewModel>();

            services.AddTransient<MediumTermPlanViewModel>();
            services.AddTransient<PlanSuggestionsIndexViewModel>();
            services.AddTransient<PlanSuggestionsDialogViewModel>();
            services.AddTransient<PlanSuggestionsDetailViewModel>();
            services.AddTransient<PlanManagerApprovedIndexViewModel>();
            services.AddTransient<PlanManagerApprovedDialogViewModel>();
            services.AddTransient<PlanManagerApprovedDetailViewModel>();

            services.AddTransient<VoucherListIndexViewModel>();
            services.AddTransient<VoucherListDialogViewModel>();
            services.AddTransient<VoucherListDetailViewModel>();
            services.AddTransient<PrintVoucherListViewModel>();
            services.AddTransient<PrintSummaryVoucherListViewModel>();
            services.AddTransient<ChuTruongDauTuIndexViewModel>();
            services.AddTransient<ChuTruongDauTuDialogViewModel>();
            services.AddTransient<GiaoDuToanChiPhiIndexViewModel>();
            services.AddTransient<GiaoDuToanChiPhiDialogViewModel>();
            services.AddTransient<GiaoDuToanChiPhiDetailViewModel>();
            services.AddTransient<TKTCVaTongDuToanIndexViewModel>();
            services.AddTransient<TKTCVaTongDuToanDialogViewModel>();
            services.AddTransient<TKTCVaTongDuToanDetailViewModel>();
            services.AddTransient<TKTCVaTongDuToanDieuChinhDialogViewModel>();
            services.AddTransient<TKTCVaTongDuToanDieuChinhDetailViewModel>();
            services.AddTransient<TKTCVaTongDuToanHangMucAllDetailViewModel>();
            services.AddTransient<TKTCVaTongDuToanHangMucDevideViewModel>();
            services.AddTransient<SysLogIndexViewModel>();
            services.AddTransient<SysLogManagementViewModel>();
            services.AddTransient<GoiThauIndexViewModel>();
            services.AddTransient<GoiThauDialogViewModel>();
            services.AddTransient<GoiThauDetailViewModel>();
            services.AddTransient<GoiThauDieuChinhViewModel>();
            services.AddTransient<GoiThauDieuChinhDetailViewModel>();
            services.AddTransient<ApproveSettlementDoneIndexViewModel>();
            services.AddTransient<ApproveSettlementDoneDialogViewModel>();
            services.AddTransient<ApproveSettlementDoneDetailViewModel>();
            services.AddTransient<ConnectDatabaseViewModel>();
            services.AddTransient<PrintReportProcessProjectViewModel>();
            services.AddTransient<PrintReportAnnualBudgetAllocationViewModel>();
            services.AddTransient<PrintReportAdjustmentPlanViewModel>();
            services.AddTransient<DuToanNSQPNamPrintReportViewModel>();
            services.AddTransient<PrintReportMediumTermPlanViewModel>();
            services.AddTransient<CapPhatThanhToanIndexViewModel>();
            services.AddTransient<CapPhatThanhToanDialogViewModel>();
            services.AddTransient<CapPhatThanhToanDetailViewModel>();
            services.AddTransient<CapPhatThanhToanImportViewModel>();
            services.AddTransient<ThanhToanKhoBacIndexViewModel>();
            services.AddTransient<ThanhToanKhoBacDialogViewModel>();
            services.AddTransient<ThanhToanKhoBacDetailViewModel>();
            services.AddTransient<KeHoachChiQuyIndexViewModel>();
            services.AddTransient<KeHoachChiQuyDialogViewModel>();
            services.AddTransient<KeHoachChiQuyDetailViewModel>();
            services.AddTransient<KeHoachChiQuyImportViewModel>();
            services.AddTransient<BaoCaoKetQuaGiaiNganChiKPDTViewModel>();
            services.AddTransient<PheDuyetThanhToanIndexViewModel>();
            services.AddTransient<PheDuyetThanhToanDialogViewModel>();
            services.AddTransient<PheDuyetThanhToanDetailViewModel>();
            services.AddTransient<PheDuyetThanhToanImportViewModel>();
            services.AddTransient<ReportIndexViewModel>();
            services.AddTransient<ReportDialogViewModel>();
            services.AddTransient<ForexPlanViewModel>();
            services.AddTransient<ForexMuaSamViewModel>();
            services.AddTransient<ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTForexContractInfo.ForexContractInfoIndexViewModel>();
            services.AddTransient<ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTForexContractInfo.ForexContractInfoItemsViewModel>();
            services.AddTransient<ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTForexContractInfo.ForexContractInfoDialogViewModel>();
            services.AddTransient<ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTForexContractInfo.ForexContractHangMucDialogViewModel>();
            services.AddTransient<ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTForexContractInfo.ForexContractInfoItemDialogViewModel>();
            services.AddTransient<MSCNTForexContractInfoIndexViewModel>();
            services.AddTransient<MSCNTForexContractInfoItemsViewModel>();
            services.AddTransient<MSCNTForexContractInfoDialogViewModel>();
            services.AddTransient<MSCNTForexContractHangMucDialogViewModel>();
            services.AddTransient<ForexDuAnViewModel>();
            services.AddTransient<ViewModel.Forex.ForexDuAn.QuanLyHopDongNhapKhau.DAHDNKForexContractInfo.ForexContractInfoIndexViewModel>();
            services.AddTransient<ViewModel.Forex.ForexDuAn.QuanLyHopDongNhapKhau.DAHDNKForexContractInfo.ForexContractInfoItemsViewModel>();
            services.AddTransient<ViewModel.Forex.ForexDuAn.QuanLyHopDongNhapKhau.DAHDNKForexContractInfo.ForexContractInfoDialogViewModel>();
            services.AddTransient<ViewModel.Forex.ForexDuAn.QuanLyHopDongNhapKhau.DAHDNKForexContractInfo.ForexContractHangMucDialogViewModel>();
            services.AddTransient<PlanOverviewIndexViewModel>();
            services.AddTransient<PlanDetailIndexViewModel>();
            services.AddTransient<ForexAllocationViewModel>();
            services.AddTransient<PlanDetailDialogViewModel>();
            services.AddTransient<ForexSettlementViewModel>();
            services.AddTransient<PlanOverviewStableDialogViewModel>();
            services.AddTransient<PlanOverviewStageDialogViewModel>();
            services.AddTransient<DmTiGiaDialogViewModel>();
            services.AddTransient<DeNghiThanhToanChiPhiIndexViewModel>();
            services.AddTransient<DeNghiThanhToanChiPhiDialogViewModel>();
            services.AddTransient<DeNghiThanhToanChiPhiDetailViewModel>();
            services.AddTransient<PrintReportKhtBhxhViewModel>();
            services.AddTransient<PrintReportKhtmBhytViewModel>();
            services.AddTransient<GetSalaryDataViewModel>();

            // thietkekythuatvatongdutoan
            services.AddTransient<ThietKeKyThuatTongDuToanItemDialogViewModel>();
            services.AddTransient<ThietKeKyThuatTongDuToanDialogViewModel>();
            services.AddTransient<ThietKeKyThuatTongDuToanHangMucDivideViewModel>();
            services.AddTransient<ThietKeKyThuatTongDuToanIndexViewModel>();
            services.AddTransient<MSNTThietKeKyThuatTongDuToanItemDialogViewModel>();
            services.AddTransient<MSNTThietKeKyThuatTongDuToanDialogViewModel>();
            services.AddTransient<MSNTThietKeKyThuatTongDuToanHangMucDivideViewModel>();
            services.AddTransient<MSNTThietKeKyThuatTongDuToanIndexViewModel>();
            services.AddTransient<MSTNThietKeKyThuatTongDuToanItemDialogViewModel>();
            services.AddTransient<MSTNThietKeKyThuatTongDuToanDialogViewModel>();
            services.AddTransient<MSTNThietKeKyThuatTongDuToanHangMucDivideViewModel>();
            services.AddTransient<MSTNThietKeKyThuatTongDuToanIndexViewModel>();
            services.AddTransient<MSCTNThietKeKyThuatTongDuToanItemDialogViewModel>();
            services.AddTransient<MSCTNThietKeKyThuatTongDuToanDialogViewModel>();
            services.AddTransient<MSCTNThietKeKyThuatTongDuToanHangMucDivideViewModel>();
            services.AddTransient<MSCTNThietKeKyThuatTongDuToanIndexViewModel>();
            services.AddTransient<ExchangeRateIndexViewModel>();
            services.AddTransient<ExchangeRateDialogViewModel>();

            services.AddTransient<MSNTKeHoachLuaChonNhaThauIndexViewModel>();
            services.AddTransient<MSNTKeHoachLuaChonNhaThauDialogViewModel>();
            services.AddTransient<MSNTKeHoachLuaChonNhaThauDetailViewModel>();
            services.AddTransient<MSTNKeHoachLuaChonNhaThauIndexViewModel>();
            services.AddTransient<MSTNKeHoachLuaChonNhaThauDialogViewModel>();
            services.AddTransient<MSTNKeHoachLuaChonNhaThauDetailViewModel>();
            services.AddTransient<MSCTNKeHoachLuaChonNhaThauIndexViewModel>();
            services.AddTransient<MSCTNKeHoachLuaChonNhaThauDialogViewModel>();
            services.AddTransient<MSCTNKeHoachLuaChonNhaThauDetailViewModel>();
            services.AddTransient<NHKeHoachLuaChonNhaThauIndexViewModel>();
            services.AddTransient<NHKeHoachLuaChonNhaThauDialogViewModel>();
            services.AddTransient<NHKeHoachLuaChonNhaThauDetailViewModel>();
            services.AddTransient<MSTNKeHoachDatHangIndexViewModel>();
            services.AddTransient<MSTNKeHoachDatHangDialogViewModel>();

            //Utilities
            services.AddTransient<UtilitiesViewModel>();
            services.AddTransient<ResetSystemViewModel>();
            services.AddTransient<BackupRestoreViewModel>();
            services.AddTransient<ScheduleIndexViewModel>();
            services.AddTransient<BackupFileIndexViewModel>();
            services.AddTransient<BackupAndRestoreViewModel>();
            services.AddTransient<ManageDataViewModel>();
            services.AddTransient<QueryDataViewModel>();
            services.AddTransient<DemandCheckAdjustmentViewModel>();
            services.AddTransient<ContractInfoIndexViewModel>();
            services.AddTransient<ContractInfoDialogViewModel>();
            services.AddTransient<HopDongDieuChinhDialogViewModel>();
            services.AddTransient<ArmyImportViewModel>();
            services.AddTransient<TongHopCanCuViewModel>();
            services.AddTransient<AllocationImportViewModel>();

            services.AddTransient<ProjectCapitalAdjustmentReportViewModel>();
            services.AddTransient<PrintReportCompareDemandCheckViewModel>();
            services.AddTransient<PrintReportYearPlanViewModel>();

            services.AddTransient<CategorySalaryViewModel>();
            services.AddTransient<PlanBeginYearDetailChildViewModel>();
            services.AddTransient<LevelBuggetIndexViewModel>();
            services.AddTransient<LevelBuggetDialogViewModel>();
            services.AddTransient<LevelBuggetDetailViewModel>();
            services.AddTransient<LevelBuggetDetailChildViewModel>();

            services.AddTransient<ForexBudgetIndexViewModel>();
            services.AddTransient<ForexBudgetDialogViewModel>();
            services.AddTransient<ForexBudgetDetailViewModel>();
            services.AddTransient<ExportForexBudgetViewModel>();
            services.AddTransient<SendDataForexBudgetViewModel>();
            services.AddTransient<ExpenseBudgetIndexViewModel>();
            services.AddTransient<ExportExpenseBudgetViewModel>();
            services.AddTransient<SendDataExpenseBudgetViewModel>();
            services.AddTransient<ExpenseBudgetDialogViewModel>();
            services.AddTransient<ExpenseBudgetDetailViewModel>();

            services.AddTransient<UpdateDataYearOfWorkViewModel>();
            services.AddTransient<SalaryTableMonthDetailViewModel>();
            services.AddTransient<InitializationViewModel>();
            services.AddTransient<InitializationProjectIndexViewModel>();
            services.AddTransient<InitializationProjectDialogViewModel>();
            services.AddTransient<InitializationProjectDetailViewModel>();

            services.AddTransient<PlanManagerApprovedImportViewModel>();
            services.AddTransient<TongHopCanCuDuToanDauNamViewModel>();
            services.AddTransient<InsuranceSalaryIndexViewModel>();
            services.AddTransient<BackPaySalaryIndexViewModel>();

            services.AddTransient<AppVersionManagementViewModel>();
            services.AddTransient<AppVersionIndexViewModel>();
            services.AddTransient<AppVersionDialogViewModel>();
            services.AddTransient<UserLnsIndexViewModel>();
            services.AddTransient<ExpertiseIndexViewModel>();
            services.AddTransient<ExpertiseDialogViewModel>();
            services.AddTransient<ExpertiseInternalDetailViewModel>();
            services.AddTransient<ExpertiseInternalIndexViewModel>();
            services.AddTransient<ExpertiseInternalDialogViewModel>();
            services.AddTransient<ExpertiseDetailViewModel>();
            services.AddTransient<ReportPreviewViewModel>();
            services.AddTransient<SalaryComparisonIndexViewModel>();
            services.AddTransient<SalaryComparisonDialogViewModel>();
            services.AddTransient<SettlementNumberIndexViewModel>();
            services.AddTransient<SettlementNumberDialogViewModel>();
            services.AddTransient<SettlementNumberDetailViewModel>();
            services.AddTransient<CadresCopyViewModel>();
            services.AddTransient<CadresCopyInMonthViewModel>();
            services.AddTransient<SalaryManagementPlanViewModel>();
            services.AddTransient<ConfigurationUpRankIndexViewModel>();
            services.AddTransient<RequestSettlementDetailViewModel>();
            services.AddTransient<MilitaryAdjustmentViewModel>();
            services.AddTransient<ApproveSettlementDoneApproveProcessViewModel>();
            services.AddTransient<ReportSumarySettlementViewModel>();
            services.AddTransient<ReportFormSettlementViewModel>();
            services.AddTransient<IncomeTaxViewModel>();
            services.AddTransient<ImportSalaryViewModel>();
            services.AddTransient<RequestSettlementImportViewModel>();
            services.AddTransient<RequestSettlementImportDialogViewModel>();
            services.AddTransient<ApproveSettlementDoneImportViewModel>();
            services.AddTransient<ApproveSettlementDoneImportDialogViewModel>();
            services.AddTransient<ExpertiseImportViewModel>();
            services.AddTransient<LevelBuggetImportViewModel>();
            services.AddTransient<DmChuKyDialogViewModel>();
            services.AddTransient<HeaderReportSoNhuCauTongHopPhuLuc1>();
            services.AddTransient<AttachmentViewModel>();
            services.AddTransient<ExpertisePrintReportCTCViewModel>();
            services.AddTransient<ExpertisePrintReportDataBySKTViewModel>();
            services.AddTransient<InitializationProcessIndexViewModel>();
            services.AddTransient<InitializationProcessDialogViewModel>();
            services.AddTransient<InitializationProcessDetailViewModel>();
            services.AddTransient<InitializationProcessImportViewModel>();
            services.AddTransient<PlanBeginYearDialogViewModel>();
            services.AddTransient<SettlementNumberInittizationDialogViewModel>();
            services.AddTransient<PlanBeginYearSummaryViewModel>();
            services.AddTransient<AllocationSummaryViewModel>();

            services.AddTransient<SettingsConfigViewModel>();
            services.AddTransient<SettingsDonViConViewModel>();
            services.AddTransient<SettingsDonViSuDungViewModel>();
            services.AddTransient<PrintReportEstimateByReceiveDivisionViewModel>();
            services.AddTransient<PlanAgencyBeginYearIndexViewModel>();
            services.AddTransient<PlanBeginYearDetailAgencyViewModel>();
            services.AddTransient<PrintReportTargetAgencySummaryViewModel>();
            services.AddTransient<PrintReportTargetMajorAgencyViewModel>();
            services.AddTransient<CadresDeleteViewModel>();
            services.AddTransient<GetDataQtThuongXuyenLuongViewModel>();
            services.AddTransient<SettlementSyntheticDialogViewModel>();
            services.AddTransient<GetLogFileViewModel>();
            services.AddTransient<ClearDataRedundancyViewModel>();
            services.AddTransient<GetDataQtQuanSoLuongViewModel>();
            services.AddTransient<BaoCaoQttxTheoCachTinhLuongViewModel>();
            services.AddTransient<PrintReportChiThuongXuyenQuocPhongViewModel>();
            services.AddTransient<CapPhatThanhToanPrintDialogViewModel>();
            services.AddTransient<ThongTriCapPhatPrintDialogViewModel>();
            services.AddTransient<PheDuyetThanhToanPrintDialogViewModel>();
            services.AddTransient<KeHoachChiQuyPrintDialogViewModel>();
            services.AddTransient<QuyetToanVDTPrintDialogViewModel>();
            services.AddTransient<RegularDataIntertationViewModel>();
            services.AddTransient<ContractorPackageIndexViewModel>();
            services.AddTransient<ContractorPackageDialogViewModel>();
            services.AddTransient<AdjustedEstimateIndexViewModel>();
            services.AddTransient<AdjustedEstimateDialogViewModel>();
            services.AddTransient<AdjustedEstimateDetailViewModel>();
            services.AddTransient<AdjustedEstimateReportViewModel>();
            services.AddTransient<AdjustedEstimateImportJsonViewModel>();
            services.AddTransient<AdjustedEstimateTheoLanReportViewModel>();
            services.AddTransient<ReportDieuChinhDuToanTongHop>();
            services.AddTransient<AdjustedEstimateImportViewModel>();
            services.AddTransient<RegularSettlementPrintDialogViewModel>();
            services.AddTransient<RegularSettlementVerbalExplanationViewModel>();
            services.AddTransient<CheckExpertiseDetailViewModel>();
            services.AddTransient<ContractorPackageHangMucDetailDialogViewModel>();
            services.AddTransient<MSCBDTForexProjectInformationIndexViewModel>();
            services.AddTransient<MSCBDTForexProjectInformationDialogViewModel>();
            services.AddTransient<DACBDTForexProjectInformationIndexViewModel>();
            services.AddTransient<DACBDTForexProjectInformationDialogViewModel>();
            services.AddTransient<DACBDTForexImportBudgetSourceDialogViewModel>();
            services.AddTransient<DACBDTForexImportCatalogDialogViewModel>();
            services.AddTransient<SuggestMlnsViewModel>();
            services.AddTransient<PrintAllocationTypeViewModel>();
            services.AddTransient<PrintReportChiTietDuToanTheoNganhViewModel>();
            services.AddTransient<DuAnQuyetDinhChiPhiKhacIndexViewModel>();
            services.AddTransient<DuAnQuyetDinhChiPhiKhacDialogViewModel>();
            services.AddTransient<MuaSamQuyetDinhChiPhiKhacIndexViewModel>();
            services.AddTransient<MuaSamQuyetDinhChiPhiKhacDialogViewModel>();

            services.AddTransient<MSNTGoiThauTrongNuocIndexViewModel>();
            services.AddTransient<MSNTGoiThauTrongNuocDialogViewModel>();
            services.AddTransient<MSNTGoiThauTrongNuocDetailViewModel>();
            services.AddTransient<MSNTGoiThauTrongNuocChiPhiViewModel>();

            services.AddTransient<MSCTNGoiThauTrongNuocDialogViewModel>();
            services.AddTransient<MSCTNGoiThauTrongNuocDetailViewModel>();
            services.AddTransient<MSCTNGoiThauTrongNuocIndexViewModel>();
            services.AddTransient<MSCTNGoiThauTrongNuocChiPhiViewModel>();


            services.AddTransient<MSTNGoiThauTrongNuocIndexViewModel>();
            services.AddTransient<MSTNGoiThauTrongNuocDialogViewModel>();
            services.AddTransient<MSTNGoiThauTrongNuocDetailViewModel>();
            services.AddTransient<MSTNGoiThauTrongNuocChiPhiViewModel>();

            services.AddTransient<ForexDomesticBiddingPackageDetailViewModel>();
            services.AddTransient<ForexDomesticBiddingPackageDialogViewModel>();
            services.AddTransient<ForexDomesticBiddingPackageIndexViewModel>();
            services.AddTransient<ForexDomesticBiddingPackageCostViewModel>();

            services.AddTransient<ImportExpertiseDistributionViewModel>();
            services.AddTransient<BudgetReportIndexViewModel>();
            services.AddTransient<MigrationDataIndexViewModel>();
            services.AddTransient<MSNTNHHopDongTrongNuocIndexViewModel>();
            services.AddTransient<MSNTNHHopDongTrongNuocDialogViewModel>();
            services.AddTransient<MSNTNHHopDongTrongNuocChiTietHangMucViewModel>();
            services.AddTransient<MSTNNHHopDongTrongNuocIndexViewModel>();
            services.AddTransient<MSTNNHHopDongTrongNuocDialogViewModel>();
            services.AddTransient<MSTNNHHopDongTrongNuocChiTietHangMucViewModel>();
            services.AddTransient<MSCTNNHHopDongTrongNuocChiTietHangMucViewModel>();
            services.AddTransient<MSCTNNHHopDongTrongNuocDialogViewModel>();
            services.AddTransient<MSCTNNHHopDongTrongNuocIndexViewModel>();
            services.AddTransient<NHHopDongTrongNuocIndexViewModel>();
            services.AddTransient<NHHopDongTrongNuocDialogViewModel>();
            services.AddTransient<NHHopDongTrongNuocChiTietHangMucViewModel>();
            services.AddTransient<ForexDeNghiThanhToanIndexViewModel>();
            services.AddTransient<ForexDeNghiThanhToanDialogViewModel>();
            services.AddTransient<ViewModel.Forex.Allocation.ForexDeNghiThanhToan.SelectMLNSDialogViewModel>();
            services.AddTransient<ForexDmNhaThauDialogViewModel>();
            services.AddTransient<ForexDmNhaThauIndexViewModel>();
            services.AddTransient<HospitalIndexViewModel>();
            services.AddTransient<HospitalDialogViewModel>();
            services.AddTransient<HospitalDetailViewModel>();
            services.AddTransient<NhuCauChiQuyIndexViewModel>();
            services.AddTransient<NhuCauChiQuyDialogViewModel>();
            services.AddTransient<NhuCauChiQuyDetailViewModel>();
            services.AddTransient<ForexPheDuyetThanhToanIndexViewModel>();
            services.AddTransient<ForexPheDuyetThanhToanDialogViewModel>();
            services.AddTransient<ViewModel.Forex.Allocation.ForexPheDuyetThanhToan.SelectMLNSDialogViewModel>();
            services.AddTransient<KHVNamDuocDuyetIndexViewModel>();
            services.AddTransient<KHVNamDuocDuyetDialogViewModel>();
            services.AddTransient<KHVNamDuocDuyetDetailViewModel>();
            services.AddTransient<KHVNamDuocDuyetReportViewModel>();
            services.AddTransient<PrintSummaryAgencyViewModel>();
            services.AddTransient<AssetIndexViewModel>();
            services.AddTransient<AssetDialogViewModel>();
            services.AddTransient<ImportSalaryTncnViewModel>();
            services.AddTransient<PrintSummaryLNSViewModel>();
            services.AddTransient<PrintReportYearSettlementSumaryYearBudgetViewModel>();
            services.AddTransient<CapPhatThanhToanTongHopDialogViewModel>();
            services.AddTransient<ForexThongTriCapPhatIndexViewModel>();
            services.AddTransient<ForexThongTriCapPhatDialogViewModel>();
            services.AddTransient<ForexTtThongTriCapPhatPrintDialogViewModel>();
            services.AddTransient<HospitalPrintReportTargetAgencyViewModel>();
            services.AddTransient<ForexTinhHinhThucHienNganSachIndexViewModel>();
            services.AddTransient<ForexTinhHinhThucHienNganSachDialogViewModel>();
            services.AddTransient<ForexTtTinhHinhThucHienNganSachPrintDialogViewModel>();
            services.AddTransient<HospitalPrintReportTargetAgencyViewModel>();
            services.AddTransient<ForexDeNghiThanhToanPrintDialogViewModel>();
            services.AddTransient<ForexPheDuyetThanhToanPrintDialogViewModel>();
            services.AddTransient<BaoCaoTinhHinhThucHienDuAnViewModel>();
            services.AddTransient<NhuCauChiQuyTongHopDialogViewModel>();
            services.AddTransient<NhuCauChiQuyPrintDialogViewModel>();

            #region QLNH - Quyết toán niên độ
            services.AddTransient<QuyetToanNienDoIndexViewModel>();
            services.AddTransient<QuyetToanNienDoDialogViewModel>();
            services.AddTransient<QuyetToanNienDoDetailViewModel>();
            services.AddTransient<QuyetToanNienDoPrintDialogViewModel>();
            services.AddTransient<QuyetToanNienDoTongHopViewModel>();
            #endregion
            services.AddTransient<PheDuyetQuyetToanDAHTIndexViewModel>();
            services.AddTransient<PheDuyetQuyetToanDAHTDialogViewModel>();
            services.AddTransient<PheDuyetQuyetToanDAHTDetailViewModel>();
            services.AddTransient<PheDuyetQuyetToanDAHTPrintDialogViewModel>();

            services.AddTransient<BaoCaoKetLuanQuyetToanIndexViewModel>();

            services.AddTransient<NHTongHopTTDuAnViewModel>();
            services.AddTransient<ImportNhaThauViewModel>();
            services.AddTransient<MSNTImportHopDongViewModel>();
            services.AddTransient<MSTNImportHopDongViewModel>();
            services.AddTransient<MSCTNImportHopDongViewModel>();
            services.AddTransient<ImportHopDongViewModel>();
            services.AddTransient<ViewModel.Forex.ForexDuAn.QuanLyHopDongNhapKhau.DAHDNKForexContractInfo.ImportHopDongNgoaiThuong.ImportHopDongNgoaiThuongViewModel>();
            services.AddTransient<ViewModel.Forex.ForexMuaSam.MuaSamNgoaiThuong.MSNTForexContractInfo.ImportHopDongNgoaiThuong.ImportHopDongNgoaiThuongViewModel>();
            services.AddTransient<MSCNTImportHopDongNgoaiThuongViewModel>();
            services.AddTransient<MSCBDTImportThongTinDuAnViewModel>();
            services.AddTransient<DACBDTImportThongTinDuAnViewModel>();
            services.AddTransient<MSNTImportGoiThauViewModel>();
            services.AddTransient<MSTNImportGoiThauViewModel>();
            services.AddTransient<MSCTNImportGoiThauViewModel>();
            services.AddTransient<ImportGoiThauViewModel>();
            services.AddTransient<RequestSettlementTongHopDialogViewModel>();
            services.AddTransient<PrintYearSettlementViewModel>();
            services.AddTransient<PrintYearApprovalSettlementViewModel>();
            services.AddTransient<PrintYearSummarySettlementViewModel>();
            services.AddTransient<AssetDetailDialogViewModel>();
            services.AddTransient<ForexDeNghiTTTongHopDialogViewModel>();
            services.AddTransient<DeNghiQTDAHTIndexViewModel>();
            services.AddTransient<DeNghiQTDAHTDialogViewModel>();
            services.AddTransient<DeNghiQTDAHTDialogDetailViewModel>();
            services.AddTransient<DeNghiQTDAHTReportDialogViewModel>();
            services.AddTransient<DeNghiQTDAHTTongHopDialogViewModel>();
            services.AddTransient<MucLucNganSachViewModel>();
            services.AddTransient<MucLucNganSachCheckDataViewModel>();
            services.AddTransient<MucLucSKTViewModel>();
            services.AddTransient<KeHoachChiQuyServerFtpViewModel>();
            services.AddTransient<BaoCaoKetLuanQuyetToanPrintDialogViewModel>();

            //services.AddTransient<PlanSuggestionsDownloadFileDialogViewModel>();
            services.AddTransient<ChuyenDuLieuQuyetToanIndexViewModel>();
            services.AddTransient<ChuyenDulieuQuyetToanDetailViewModel>();
            services.AddTransient<ChuyenDulieuQuyetToanDialogViewModel>();
            services.AddTransient<ExchangeRateDifferenceIndexViewModel>();
            services.AddTransient<ExchangeRateDifferencePrintDialogViewModel>();
            services.AddTransient<ViewModel.Forex.ForexSettlement.ThongTriQuyetToan.ThongTriQuyetToanIndexViewModel>();
            services.AddTransient<ViewModel.Forex.ForexSettlement.ThongTriQuyetToan.ThongTriQuyetToanDialogViewModel>();
            services.AddTransient<BaoCaoTaiSanIndexViewModel>();
            services.AddTransient<BaoCaoTaiSanExportDialogViewModel>();
            services.AddTransient<ThongTriQuyetToanPrintDialogViewModel>();

            //Khoi Tao Cap Phat
            services.AddTransient<ForexKhoiTaoCapPhatViewModel>();
            services.AddTransient<ForexDanhSachKhoiTaoDialogViewModel>();
            services.AddTransient<ForexDanhSachKhoiTaoDetailViewModel>();
            services.AddTransient<ForexDanhSachKhoiTaoIndexViewModel>();
            services.AddTransient<ForexDanhSachKhoiTaoImportViewModel>();
            services.AddTransient<ForexKhoiTaoTheoQuyetDinhIndexViewModel>();
            services.AddTransient<ForexKhoiTaoTheoQuyetDinhImportViewModel>();
            services.AddTransient<ForexKhoiTaoTheoQuyetDinhDialogViewModel>();
            services.AddTransient<ForexKhoiTaoTheoQuyetDinhDetailViewModel>();


            services.AddTransient<MSCBDTInvestmentPolicyDialogViewModel>();
            services.AddTransient<MSCBDTInvestmentPolicyIndexViewModel>();

            services.AddTransient<MSNTDecisionDialogDetailItemsViewModel>();
            services.AddTransient<MSNTDecisionDialogDetailViewModel>();
            services.AddTransient<MSNTDecisionDialogViewModel>();
            services.AddTransient<MSNTDecisionHangMucDetailDialogViewModel>();
            services.AddTransient<MSNTDecisionIndexViewModel>();

            services.AddTransient<MSPCNTDecisionDialogDetailItemsViewModel>();
            services.AddTransient<MSPCNTDecisionDialogDetailViewModel>();
            services.AddTransient<MSPCNTDecisionDialogViewModel>();
            services.AddTransient<MSPCNTDecisionHangMucDetailDialogViewModel>();
            services.AddTransient<MSPCNTDecisionIndexViewModel>();

            services.AddTransient<MSCBDTInvestmentDecisionDialogViewModel>();
            services.AddTransient<MSCBDTInvestmentDecisionIndexViewModel>();
            services.AddTransient<MSCBDTInvestmentDecisionItemDialogViewModel>();

            services.AddTransient<DACBDTInvestmentPolicyDialogViewModel>();
            services.AddTransient<DACBDTInvestmentPolicyIndexViewModel>();

            services.AddTransient<DAHDNKDecisionDialogDetailItemsViewModel>();
            services.AddTransient<DAHDNKDecisionDialogDetailViewModel>();
            services.AddTransient<DAHDNKDecisionDialogViewModel>();
            services.AddTransient<DAHDNKDecisionHangMucDetailDialogViewModel>();
            services.AddTransient<DAHDNKDecisionIndexViewModel>();

            services.AddTransient<DACBDTInvestmentDecisionDialogViewModel>();
            services.AddTransient<DACBDTInvestmentDecisionIndexViewModel>();
            services.AddTransient<DACBDTInvestmentDecisionItemDialogViewModel>();

            services.AddTransient<DANHPhuongAnNhapKhauDetailViewModel>();
            services.AddTransient<DANHPhuongAnNhapKhauDialogViewModel>();
            services.AddTransient<DANHPhuongAnNhapKhauIndexViewModel>();
            services.AddTransient<DANHPhuongAnNhapKhauItemDialogViewModel>();

            services.AddTransient<MSNHPhuongAnNhapKhauDetailViewModel>();
            services.AddTransient<MSNHPhuongAnNhapKhauDialogViewModel>();
            services.AddTransient<MSNHPhuongAnNhapKhauIndexViewModel>();
            services.AddTransient<MSNHPhuongAnNhapKhauItemDialogViewModel>();

            services.AddTransient<MSNTNHPhuongAnNhapKhauDetailViewModel>();
            services.AddTransient<MSNTNHPhuongAnNhapKhauDialogViewModel>();
            services.AddTransient<MSNTNHPhuongAnNhapKhauIndexViewModel>();
            services.AddTransient<MSNTNHPhuongAnNhapKhauItemDialogViewModel>();

            services.AddTransient<MSTNHopDongTrongNuocKhongGoiThauIndexViewModel>();
            services.AddTransient<MSTNHopDongTrongNuocKhongGoiThauDialogViewModel>();

            services.AddTransient<ContractInfoImportViewModel>();
            services.AddTransient<GoiThauImportViewModel>();
            services.AddTransient<MSTNImportHopDongKhongGoiThauViewModel>();

            services.AddTransient<SocialInsuranceViewModel>();
            services.AddTransient<LapKeHoachChiIndexViewModel>();
            services.AddTransient<LapKeHoachChiDialogViewModel>();
            services.AddTransient<LapKeHoachChiDetailViewModel>();
            services.AddTransient<KeHoachThuIndexViewModel>();
            services.AddTransient<KeHoachThuDialogViewModel>();
            services.AddTransient<KeHoachThuDetailViewModel>();
            services.AddTransient<ImportGetSalaryDataViewModel>();
            services.AddTransient<DuToanThuBHXHIndexViewModel>();
            services.AddTransient<DuToanThuBHXHDialogViewModel>();
            services.AddTransient<DuToanThuBHXHDetailViewModel>();
            services.AddTransient<SocialInsurancePlanViewModel>();
            services.AddTransient<SocialInsuranceEstimateViewModel>();
            services.AddTransient<ImportKhtBHXHViewModel>();
            services.AddTransient<ImportKhcBHXHViewModel>();
            services.AddTransient<PrintReportLapKeHoachChiViewModel>();
            services.AddTransient<KeHoachThuMuaBHYTIndexViewModel>();
            services.AddTransient<KeHoachThuMuaBHYTDialogViewModel>();
            services.AddTransient<LapKeHoachChiQuanLyIndexViewModel>();
            services.AddTransient<LapKeHoachChiQuanLyDialogViewModel>();
            services.AddTransient<LapKeHoachChiQuanLyDetailViewModel>();

            services.AddTransient<NhanDuToanChiTrenGiaoIndexViewModel>();
            services.AddTransient<NhanDuToanChiTrenGiaoDialogViewModel>();
            services.AddTransient<NhanDuToanChiTrenGiaoDetailViewModel>();
            services.AddTransient<PrintReportNhanDuToanChiTrenGiaoViewModel>();
            services.AddTransient<ImportNdtctgBHXHViewModel>();

            services.AddTransient<KeHoachThuMuaBHYTDetailViewModel>();
            services.AddTransient<ImportKhtmBHYTViewModel>();
            services.AddTransient<ImportKhcQuanLyKinhPhiViewModel>();
            services.AddTransient<PrintReportQuanLyKinhPhiViewModel>();
            services.AddTransient<DuToanThuBHXHImportViewModel>();
            services.AddTransient<LapKeHoachChiKhacIndexViewModel>();
            services.AddTransient<LapKeHoachChiKhacDialogViewModel>();
            services.AddTransient<LapKeHoachChiKhacDetailViewModel>();
            services.AddTransient<ImportKhcKViewModel>();
            services.AddTransient<PrintReportKhcKViewModel>();

            services.AddTransient<PhanBoDuToanChiIndexViewModel>();
            services.AddTransient<PhanBoDuToanChiDialogViewModel>();
            services.AddTransient<PhanBoDuToanChiDetailViewModel>();
            services.AddTransient<MucLucNganSachBHXHViewModel>();
            services.AddTransient<PhuCapDialogViewModel>();
            services.AddTransient<DieuChinhDuToanBHXHIndexViewModel>();
            services.AddTransient<DieuChinhDuToanBHXHDialogViewModel>();
            services.AddTransient<DieuChinhDuToanBHXHDetailViewModel>();
            services.AddTransient<ImportDieuChinhDuToanBHXHViewModel>();
            services.AddTransient<PrintReportDieuChinhDuToanViewModel>();
            services.AddTransient<PrintReportDieuChinhDuToanTheoLanViewModel>();
            services.AddTransient<ExportPhanBoDuToanChiViewModel>();
            services.AddTransient<PhanBoDuToanThuDetailViewModel>();
            services.AddTransient<PhanBoDuToanThuDialogViewModel>();
            services.AddTransient<PhanBoDuToanThuIndexViewModel>();
            services.AddTransient<ExportPhanBoDuToanThuViewModel>();
            services.AddTransient<NhanPhanBoDuToanThuBHYTIndexViewModel>();
            services.AddTransient<PhanBoDuToanThuMuaBHYTIndexViewModel>();
            services.AddTransient<PhanBoDuToanThuMuaBHYTDialogViewModel>();
            services.AddTransient<PhanBoDuToanThuMuaBHYTDetailViewModel>();
            services.AddTransient<ExportPhanBoDuToanThuMuaBHYTViewModel>();
            services.AddTransient<DieuChinhDuToanThuIndexViewModel>();
            services.AddTransient<DieuChinhDuToanThuDialogViewModel>();
            services.AddTransient<DieuChinhDuToanThuDetailViewModel>();
            services.AddTransient<NhanPhanBoDuToanThuBHYTDialogViewModel>();
            services.AddTransient<NhanPhanBoDuToanThuBHYTDetailViewModel>();
            services.AddTransient<NhanPhanBoDuToanThuBHYTImportlViewModel>();
            services.AddTransient<ForexDeNghiThanhToanImportViewModel>();
            services.AddTransient<SocialInsuranceAllocationViewModel>();
            services.AddTransient<DieuChinhDuToanThuImportViewModel>();
            services.AddTransient<PrintReportDieuChinhDuToanThuViewModel>();
            services.AddTransient<CapPhatTamUngKCBBHYTIndexViewModel>();
            services.AddTransient<CapPhatTamUngKCBBHYTDialogViewModel>();
            services.AddTransient<CapPhatTamUngKCBBHYTDetailViewModel>();
            services.AddTransient<CapPhatBoSungDetailViewModel>();
            services.AddTransient<CapPhatBoSungDialogViewModel>();
            services.AddTransient<CapPhatBoSungIndexViewModel>();
            services.AddTransient<CapPhatTamUngKCBBHYTSummaryViewModel>();
            services.AddTransient<PrintCapPhatTamUngKCBBHYTViewModel>();
            services.AddTransient<ExportCapPhatTamUngKCBBHYTViewModel>();
            services.AddTransient<ImportCapPhatTamUngBHYTViewModel>();
            services.AddTransient<CapPhatBoSungImportViewModel>();
            services.AddTransient<ChungTuCapPhatIndexViewModel>();
            services.AddTransient<ChungTuCapPhatDialogViewModel>();
            services.AddTransient<ChungTuCapPhatDetailViewModel>();
            services.AddTransient<ImportChungTuCapPhatViewModel>();
            services.AddTransient<PrintChungTuCapPhatNoticeViewModel>();
            services.AddTransient<PrintChungTuCapPhatDonViViewModel>();
            services.AddTransient<CapPhatBoSungReportViewModel>();
            services.AddTransient<QuyetToanThuDetailViewModel>();
            services.AddTransient<QuyetToanThuDialogViewModel>();
            services.AddTransient<QuyetToanThuIndexViewModel>();
            services.AddTransient<QuyetToanThuImportViewModel>();

            services.AddTransient<SocialInsuranceSettlementViewModel>();
            services.AddTransient<QuyetToanChiKinhPhiQuanLyIndexViewModel>();
            services.AddTransient<QuyetToanChiKinhPhiQuanLyDialogViewModel>();
            services.AddTransient<QuyetToanChiKinhPhiQuanLyDetailViewModel>();
            services.AddTransient<QuyetToanChiNamBHXHIndexViewModel>();
            services.AddTransient<QuyetToanChiNamBHXHDialogViewModel>();
            services.AddTransient<QuyetToanChiNamBHXHDetailViewModel>();
            services.AddTransient<QuyetToanChiNamBHXHSummaryViewModel>();
            services.AddTransient<QuyetToanChiQuyBHXHIndexViewModel>();
            services.AddTransient<QuyetToanChiQuyBHXHDetailViewModel>();
            services.AddTransient<QuyetToanChiQuyBHXHDialogViewModel>();
            services.AddTransient<QuyetToanChiQuyBHXHSummaryViewModel>();
            services.AddTransient<PrintQuyetToanChiQuyBHXHViewModel>();
            services.AddTransient<ImportQuyetToanChiQuyBHXHViewModel>();
            services.AddTransient<CongThucImportViewModel>();
            services.AddTransient<ImportQuyetToanChiNamBHXHViewModel>();
            services.AddTransient<ImportQuyetToanChiKinhPhiQuanLyViewModel>();
            services.AddTransient<PrintQuyetToanChiNamBHXHViewModel>();
            services.AddTransient<PrintNhanVaQuyetToanChiNamBHXHViewModel>();
            services.AddTransient<PrintQuyetToanChiKinhPhiQuanLyNoticeViewModel>();
            services.AddTransient<QuyetToanNamChiKinhPhiQuanLyIndexViewModel>();
            services.AddTransient<QuyetToanNamChiKinhPhiQuanLyDialogViewModel>();
            services.AddTransient<PrintQuyetToanThuViewModel>();
            services.AddTransient<QuyetToanThuMuaIndexViewModel>();
            services.AddTransient<QuyetToanThuMuaDialogViewModel>();
            services.AddTransient<QuyetToanThuMuaDetailViewModel>();
            services.AddTransient<PrintQuyetToanThuMuaViewModel>();
            services.AddTransient<QuyetToanThuMuaImportViewModel>();
            services.AddTransient<QuyetToanNamChiKinhPhiQuanLyDetailViewModel>();
            services.AddTransient<QuyetToanChiQuyKCBIndexViewModel>();
            services.AddTransient<QuyetToanChiQuyKCBDetailViewModel>();
            services.AddTransient<QuyetToanChiQuyKCBDialogViewModel>();
            services.AddTransient<QuyetToanChiQuyKCBSummaryViewModel>();
            services.AddTransient<ImportQuyetToanChiQuyKCBViewModel>();
            services.AddTransient<PrintQuyetToanChiQuyKCBViewModel>();
            services.AddTransient<ImportQuyetToanChiNamKinhPhiQuanLyViewModel>();
            services.AddTransient<PrintQuyetToanChiNamKinhPhiQuanLyNoticeViewModel>();
            services.AddTransient<DemandCheckAdjustmentViewModel>();
            services.AddTransient<QuyetToanChiQuyKinhPhiKhacIndexViewModel>();
            services.AddTransient<QuyetToanChiQuyKinhPhiKhacDialogViewModel>();
            services.AddTransient<QuyetToanChiQuyKinhPhiKhacDetailViewModel>();
            services.AddTransient<ImportQuyetToanChiQuyKinhPhiKhacViewModel>();
            services.AddTransient<PrintQuyetToanChiQuyKinhPhiKhacNoticeViewModel>();
            services.AddTransient<QuyetToanNamChiKinhPhiKhacIndexViewModel>();
            services.AddTransient<QuyetToanNamChiKinhPhiKhacDialogViewModel>();
            services.AddTransient<QuyetToanNamChiKinhPhiKhacDetailViewModel>();
            services.AddTransient<ImportQuyetToanNamChiKinhPhiKhacViewModel>();
            services.AddTransient<PrintQuyetToanChiNamKinhPhiKhacNoticeViewModel>();
            services.AddTransient<LapKeHoachChiKCBQYDVIndexViewModel>();
            services.AddTransient<LapKeHoachChiKCBQYDVDialogViewModel>();
            services.AddTransient<LapKeHoachChiKCBQYDVDetailViewModel>();
            services.AddTransient<ImportKhcKCBQYDVViewModel>();
            services.AddTransient<PrintReportKhcKCBQYDVViewModel>();

            services.AddTransient<QuyetToanChiNamKCBIndexViewModel>();
            services.AddTransient<QuyetToanChiNamKCBDialogViewModel>();
            services.AddTransient<QuyetToanChiNamKCBDetailViewModel>();
            services.AddTransient<QuyetToanChiNamKCBSummaryViewModel>();
            services.AddTransient<ImportQuyetToanChiNamKCBViewModel>();
            services.AddTransient<PrintQuyetToanChiNamKCViewModel>();
            services.AddTransient<QuyetToanThuGiaiThichBangLoiViewModel>();
            services.AddTransient<QuyetToanThuGiaiThichSoLieuViewModel>();
            services.AddTransient<QuyetToanCapKinhPhiKcbIndexViewModel>();
            services.AddTransient<QuyetToanCapKinhPhiKcbDialogViewModel>();
            services.AddTransient<QuyetToanCapKinhPhiKcbDetailViewModel>();
            services.AddTransient<QuyetToanCapKinhPhiKcbImportViewModel>();
            services.AddTransient<ImportPheDuyetDuAnViewModel>();
            services.AddTransient<ImportTKTCVaTongDuToanViewModel>();
            services.AddTransient<CategoryHolidayIndexViewModel>();
            services.AddTransient<CategoryHolidayDialogViewModel>();
            services.AddTransient<InsuranceSalaryReportViewModel>();
            services.AddTransient<InsuranceSalaryExportViewModel>();
            services.AddTransient<ImportQTCQBHXHExplanationViewModel>();
            services.AddTransient<TongHopThuChiViewModel>();
            services.AddTransient<SocialInsurancePlanReportIndexViewModel>();
            services.AddTransient<SocialInsuranceEstimateReportIndexViewModel>();
            services.AddTransient<SocialInsuranceEstimateAdjustReportIndexViewModel>();
            services.AddTransient<SocialInsuranceAllocationReportIndexViewModel>();
            services.AddTransient<SocailInsuranceSettlementReportIndexViewModel>();
            services.AddTransient<SocailInsuranceSettlementReportQuarterIndexViewModel>();
            services.AddTransient<ThamDinhQuyetToanIndexViewModel>();
            services.AddTransient<ThamDinhQuyetToanDialogViewModel>();
            services.AddTransient<ThamDinhQuyetToanDetailViewModel>();
            services.AddTransient<SocailInsuranceSettlementReportYearIndexViewModel>();
            services.AddTransient<SocialInsuranceSettlementReportGeneralIndexViewModel>();
            services.AddTransient<CadresBHXHViewModel>();
            services.AddTransient<PrintPhanBoTuToanChiTheoDonViViewModel>();
            services.AddTransient<PrintPhuLucDuToanThuViewModel>();
            services.AddTransient<PrintPhuLucDuToanThuMuaBHYTViewModel>();
            services.AddTransient<PrintQuyetToanCapKinhPhiKCBBHYTViewModel>();
            services.AddTransient<BhBaoCaoGhiChuDialogViewModel>();
            services.AddTransient<PrintThamDinhTongHopThuChiViewModel>();
            services.AddTransient<InsuranceSalaryAggregateViewModel>();
            services.AddTransient<QuyetToanChiGiaiThichBangLoiQuyBHXHViewModel>();
            services.AddTransient<QuyetToanChiGiaiThichBangLoiQuyKPQLViewModel>();
            services.AddTransient<QuyetToanChiGiaiThichBangLoiQuyKCBViewModel>();
            services.AddTransient<QuyetToanChiGiaiThichBangLoiQuyKhacViewModel>();
            return services;
        }

        public static IServiceCollection AddTransientFromNamespace(this IServiceCollection services)
        {
            string name = "VTS.QLNS.CTC.App";
            string namespaceName = $"{name}.ViewModel";
            var assemblies = AppDomain.CurrentDomain.GetAssemblies().Where(x => x.FullName.StartsWith(name)).ToArray();
            foreach (var assembly in assemblies)
            {
                var types = assembly.GetTypes().Where(x => x.Namespace != null
                    && !x.IsAbstract
                    && x.Namespace.StartsWith(namespaceName, System.StringComparison.InvariantCultureIgnoreCase));
                foreach (var type in types)
                {
                    if (services.All(x => x.ServiceType != type))
                    {
                        services.AddTransient(type);
                    }
                }
            }
            return services;
        }
    }
}
