using System;
using System.Collections.Generic;
using System.Text;

namespace VTS.QLNS.CTC.App.Model
{
    public class AutoGenerateDataSetting
    {
        public List<ModelSetting> ModelSettings { get; set; }
    }

    public class ModelSetting
    {
        public string ModelName { get; set; }
        public List<PropertySetting> PropertySettings { get; set; }
    }

    public class PropertySetting
    {
        public string PropName { get; set; }
        public string FormatVal { get; set; }
    }
}
