using System;
using System.Collections.Generic;
using System.Linq;
using VTS.QLNS.CTC.App.Model;
using VTS.QLNS.CTC.Core.Domain;
using VTS.QLNS.CTC.Utility;

namespace VTS.QLNS.CTC.App.Service.Impl
{
    public class SessionService : ISessionService
    {
        public event Action StateChanged;

        private SessionInfo _current;
        public SessionInfo Current
        {
            get => _current;
            set
            {
                _current = value;
                StateChanged?.Invoke();
            }
        }
    }

    public class SessionInfo : BindableBase
    {
        public string Principal { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName => string.Format("{0} {1}", FirstName, LastName);
        public string Email { get; set; }

        private string _imageUrl;
        public string ImageUrl
        {
            get => _imageUrl;
            set => SetProperty(ref _imageUrl, value);
        }

        public string IdDonVi { get; set; }
        public string TenDonVi { get; set; }
        public string TenDonViReportHeader => StringUtils.GetValue(TenDonVi).ToUpper();
        public string TenDonViTrucThuoc { get; set; }
        public string TenDonViTrucThuocReportHeader => StringUtils.GetValue(TenDonViTrucThuoc).ToUpper();
        public string TenDanhMucDiaDiem { get; set; }
        public string TenDanhMucDiaDiemReportHeader => StringUtils.GetValue(TenDanhMucDiaDiem).ToUpper();

        public List<string> Authorities { get; set; }

        private int _yearOfBudget;
        public int YearOfBudget
        {
            // 1: Năm trước đã cấp, 2: Năm nay, 3: Năm trước chưa cấp
            get => _yearOfBudget;
            set
            {
                _yearOfBudget = value;
                OnPropertyChanged(nameof(YearOfBudgetStr));
            }
        }

        public string YearOfBudgetStr => "Năm ngân sách: " + _yearOfBudget switch
        {
            1 => "1 - Năm trước đã cấp",
            2 => "2 - Năm nay",
            3 => "3 - Năm trước chuyển sang",
            4 => "4 - Năm trước chưa cấp",
            _ => ""
        };

        private int _yearOfWork;
        public int YearOfWork
        {
            get => _yearOfWork;
            set
            {
                _yearOfWork = value;
                OnPropertyChanged(nameof(Time));
            }
        }

        private int _month;
        public int Month
        {
            get => _month;
            set
            {
                _month = value;
                OnPropertyChanged(nameof(Time));
            }
        }

        public string Time
        {
            get => "Tháng/Năm : " + Month.ToString("D2") + " - " + YearOfWork.ToString("D4");
        }

        private int _budget;
        public int Budget
        {
            get => _budget;
            set
            {
                _budget = value;
                OnPropertyChanged(nameof(BudgetStr));
            }
        }

        public string BudgetStr
        {
            get
            {
                string str = "Nguồn ngân sách: ";
                switch (_budget)
                {
                    case 1:
                        str += "1 - Ngân sách quốc phòng";
                        break;
                    case 2:
                        str += "2 - Ngân sách nhà nước";
                        break;
                    case 5:
                        str += "5 - Ngân sách địa phương";
                        break;
                    case 8:
                        str += "8 - Nguồn Dự phòng";
                        break;
                    case 9:
                        str += "9 - BHXH, YT, TN";
                        break;
                    default:
                        break;
                }
                return str;
            }
        }

        public string IdsDonViQuanLy { get; set; }
        public string IdsPhanHoQuanLy { get; set; }

        public List<DonVi> DonViQuanLy { get; set; }
        public bool IsQuanLyDonViCha => IdsDonViQuanLy.Split(",").Contains(IdDonVi);

        public Dictionary<string, Dictionary<string, string>> AutoGenerateDataSetting { get; set; }
        public Dictionary<string, List<string>> FuncAuthorities { get; set; }
        public ICollection<HtNhomNguoiDung> SysGroupUsers { get; set; }

        private string _dbname;
        public string DbName
        {
            get => _dbname;
            set => SetProperty(ref _dbname, value);
        }

        private string _dbVersion;
        public string DbVersion
        {
            get => _dbVersion;
            set => SetProperty(ref _dbVersion, value);
        }
    }
}
