namespace VTS.QLNS.CTC.Utility
{
    public struct NSFunctionCode
    {
        public const string CATEGORY = "CATEGORY";

        public const string CATEGORY_GENERAL = "CATEGORY_GENERAL";
        public const string CATEGORY_GENERAL_DONVI = "CATEGORY_GENERAL_DONVI";
        public const string CATEGORY_GENERAL_PHONGBAN = "CATEGORY_GENERAL_PHONGBAN";
        public const string CATEGORY_GENERAL_CFG_SYSTEM = "CATEGORY_GENERAL_CFG_SYSTEM";
        public const string CATEGORY_GENERAL_SIGN = "CATEGORY_GENERAL_SIGN";
        public const string CATEGORY_GENERAL_SIGN_GROUP = "CATEGORY_GENERAL_SIGN_GROUP";
        public const string CATEGORY_GENERAL_CFG_CANCU = "CATEGORY_GENERAL_CFG_CANCU";
        public const string CATEGORY_GENERAL_CFG_CHUYENDE = "CATEGORY_GENERAL_CFG_CHUYENDE";

        public const string CATEGORY_BUDGET = "CATEGORY_BUDGET";
        public const string CATEGORY_BUDGET_MLNS = "CATEGORY_BUDGET_MLNS";
        public const string CATEGORY_BUDGET_MLQS = "CATEGORY_BUDGET_MLQS";
        public const string CATEGORY_BUDGET_MLSKT = "CATEGORY_BUDGET_MLSKT";
        public const string CATEGORY_BUDGET_ALLOCATION = "CATEGORY_BUDGET_ALLOCATION";
        public const string CATEGORY_BUDGET_CNG = "CATEGORY_BUDGET_CNG";
        public const string CATEGORY_BUDGET_NGANH = "CATEGORY_BUDGET_NGANH";
        public const string CATEGORY_BUDGET_CFG_MLNS = "CATEGORY_BUDGET_CFG_MLNS";

        public const string CATEGORY_INVESTMENT = "CATEGORY_INVESTMENT";
        public const string CATEGORY_INVESTMENT_CONG_TRINH = "CATEGORY_INVESTMENT_CONG_TRINH";
        public const string CATEGORY_INVESTMENT_CHI_PHI = "CATEGORY_INVESTMENT_CHI_PHI";
        public const string CATEGORY_INVESTMENT_NHA_THAU = "CATEGORY_INVESTMENT_NHA_THAU";
        public const string CATEGORY_INVESTMENT_CDT = "CATEGORY_INVESTMENT_CDT";
        public const string CATEGORY_INVESTMENT_DON_VI_THUC_HIEN = "CATEGORY_INVESTMENT_DON_VI_THUC_HIEN";

        public const string CATEGORY_SALARY = "CATEGORY_SALARY";
        public const string CATEGORY_SALARY_SYSTEM_CFG = "CATEGORY_SALARY_SYSTEM_CFG";
        public const string CATEGORY_SALARY_CHUC_VU = "CATEGORY_SALARY_CHUC_VU";
        public const string CATEGORY_SALARY_CHUC_DANH = "CATEGORY_SALARY_CHUC_DANH";
        public const string CATEGORY_SALARY_KINH_PHI = "CATEGORY_SALARY_KINH_PHI";
        public const string CATEGORY_SALARY_THUE_TN = "CATEGORY_SALARY_THUE_TN";
        public const string CATEGORY_SALARY_TANG_GIAM = "CATEGORY_SALARY_TANG_GIAM";
        public const string CATEGORY_SALARY_PHU_CAP = "CATEGORY_SALARY_PHU_CAP";
        public const string CATEGORY_SALARY_CAP_BAC = "CATEGORY_SALARY_CAP_BAC";
        public const string CATEGORY_SALARY_DON_VI = "CATEGORY_SALARY_DON_VI";
        public const string CATEGORY_SALARY_CHE_DO_BHXH = "CATEGORY_SALARY_PHU_CAP";
        public const string CATEGORY_SALARY_HOLIDAY = "CATEGORY_SALARY_PHU_CAP";

        public const string CATEGORY_NEW_SALARY = "CATEGORY_NEW_SALARY";
        public const string CATEGORY_NEW_SALARY_SYSTEM_CFG = "CATEGORY_NEW_SALARY_SYSTEM_CFG";
        public const string CATEGORY_NEW_SALARY_CHUC_VU = "CATEGORY_NEW_SALARY_CHUC_VU";
        public const string CATEGORY_NEW_SALARY_CHUC_DANH = "CATEGORY_NEW_SALARY_CHUC_DANH";
        public const string CATEGORY_NEW_SALARY_KINH_PHI = "CATEGORY_NEW_SALARY_KINH_PHI";
        public const string CATEGORY_NEW_SALARY_THUE_TN = "CATEGORY_NEW_SALARY_THUE_TN";
        public const string CATEGORY_NEW_SALARY_TANG_GIAM = "CATEGORY_NEW_SALARY_TANG_GIAM";
        public const string CATEGORY_NEW_SALARY_PHU_CAP = "CATEGORY_NEW_SALARY_PHU_CAP";
        public const string CATEGORY_NEW_SALARY_CAP_BAC = "CATEGORY_NEW_SALARY_CAP_BAC";
        public const string CATEGORY_NEW_SALARY_DON_VI = "CATEGORY_NEW_SALARY_DON_VI";
        public const string CATEGORY_NEW_SALARY_CHE_DO_BHXH = "CATEGORY_NEW_SALARY_PHU_CAP";

        public const string CATEGORY_NNS = "CATEGORY_NNS";

        public const string CATEGORY_FOREX = "CATEGORY_FOREX";
        public const string CATEGORY_FOREX_CURRENCY = "CATEGORY_FOREX_CURRENCY";
        public const string CATEGORY_FOREX_EXCHANGE_RATE = "CATEGORY_FOREX_EXCHANGE_RATE";
        public const string CATEGORY_FOREX_MISSION = "CATEGORY_FOREX_MISSION";
        public const string CATEGORY_FOREX_COST = "CATEGORY_FOREX_COST";
        public const string CATEGORY_FOREX_NHA_THAU = "CATEGORY_FOREX_NHA_THAU";

        public const string SYSTEM = "SYSTEM";

        public const string SYSTEM_SYSLOG = "SYSTEM_SYSLOG";
        public const string SYSTEM_SYSLOG_INDEX = "SYSTEM_SYSLOG_INDEX";

        public const string SYSTEM_USER_MANAGEMENT = "SYSTEM_USER_MANAGEMENT";
        public const string SYSTEM_USER_MANAGEMENT_USER_INDEX = "SYSTEM_USER_MANAGEMENT_USER_INDEX";
        public const string SYSTEM_USER_MANAGEMENT_GROUP_INDEX = "SYSTEM_USER_MANAGEMENT_GROUP_INDEX";
        public const string SYSTEM_USER_MANAGEMENT_USER_LNS_INDEX = "SYSTEM_USER_MANAGEMENT_USER_LNS_INDEX";
        public const string SYSTEM_USER_DANH_SACH_CHUC_NANG = "SYSTEM_USER_DANH_SACH_CHUC_NANG";
        public const string SYSTEM_USER_CAU_HINH_QUYEN_CHUC_NANG = "SYSTEM_USER_CAU_HINH_QUYEN_CHUC_NANG";

        public const string SYSTEM_BACKUP_RESTORE = "SYSTEM_BACKUP_RESTORE";
        public const string SYSTEM_BACKUP_RESTORE_FILE_INDEX = "SYSTEM_BACKUP_RESTORE_FILE_INDEX";
        public const string SYSTEM_BACKUP_RESTORE_SCHEDULE_INDEX = "SYSTEM_BACKUP_RESTORE_SCHEDULE_INDEX";

        public const string SYSTEM_UTILITIES = "SYSTEM_UTILITIES";
        public const string SYSTEM_UTILITIES_MANAGE_DATA = "SYSTEM_UTILITIES_MANAGE_DATA";
        public const string SYSTEM_UTILITIES_QUERY_DATA = "SYSTEM_UTILITIES_QUERY_DATA";

        public const string BUDGET = "BUDGET";
        public const string BUDGET_ALLOCATION = "BUDGET_ALLOCATION";
        public const string BUDGET_ALLOCATION_RECEIVE = "BUDGET_ALLOCATION_RECEIVE";
        public const string BUDGET_ALLOCATION_INDEX = "BUDGET_ALLOCATION_INDEX";
        public const string BUDGET_ALLOCATION_INDEX_ADD_EDIT = "BUDGET_ALLOCATION_INDEX_ADD_EDIT";
        public const string BUDGET_ALLOCATION_INDEX_LOCK = "BUDGET_ALLOCATION_INDEX_LOCK";
        public const string BUDGET_ALLOCATION_INDEX_DELETE = "BUDGET_ALLOCATION_INDEX_DELETE";
        public const string BUDGET_ALLOCATION_INDEX_PRINT = "BUDGET_ALLOCATION_INDEX_PRINT";
        public const string BUDGET_ALLOCATION_INDEX_EXCEL = "BUDGET_ALLOCATION_INDEX_EXCEL";
        public const string BUDGET_ALLOCATION_INDEX_SUMMARY = "BUDGET_ALLOCATION_INDEX_SUMMARY";
        public const string BUDGET_ALLOCATION_DETAIL_ADD = "BUDGET_ALLOCATION_DETAIL_ADD";
        public const string BUDGET_ALLOCATION_DETAIL_SAVE = "BUDGET_ALLOCATION_DETAIL_SAVE";
        public const string BUDGET_ALLOCATION_DETAIL_DELETE = "BUDGET_ALLOCATION_DETAIL_DELETE";
        public const string BUDGET_ALLOCATION_DETAIL_LOCK = "BUDGET_ALLOCATION_DETAIL_LOCK";
        public const string BUDGET_ALLOCATION_DETAIL_PRINT = "BUDGET_ALLOCATION_DETAIL_PRINT";
        public const string BUDGET_DEMANDCHECK_PLAN_INDEX_DETAIL = "BUDGET_DEMANDCHECK_PLAN_INDEX_DETAIL";
        public const string BUDGET_DEMANDCHECK_PLAN_INDEX_LOCK = "BUDGET_DEMANDCHECK_PLAN_INDEX_LOCK";
        public const string BUDGET_DEMANDCHECK_PLAN_INDEX_PRINT = "BUDGET_DEMANDCHECK_PLAN_INDEX_PRINT";
        public const string BUDGET_DEMANDCHECK_PLAN_INDEX_EXCEL = "BUDGET_DEMANDCHECK_PLAN_INDEX_EXCEL";
        public const string BUDGET_DEMANDCHECK_PLAN_INDEX_EDIT = "BUDGET_DEMANDCHECK_PLAN_INDEX_EDIT";
        public const string BUDGET_DEMANDCHECK_PLAN_INDEX_SUMMARY = "BUDGET_DEMANDCHECK_PLAN_INDEX_SUMMARY";
        public const string BUDGET_DEMANDCHECK_PLAN_DETAIL_SAVE = "BUDGET_DEMANDCHECK_PLAN_DETAIL_SAVE";
        public const string BUDGET_DEMANDCHECK_PLAN_DETAIL_DELETE = "BUDGET_DEMANDCHECK_PLAN_DETAIL_DELETE";
        public const string BUDGET_DEMANDCHECK_PLAN_DETAIL_COPY = "BUDGET_DEMANDCHECK_PLAN_DETAIL_COPY";
        public const string BUDGET_DEMANDCHECK_PLAN_DETAIL_PRINT = "BUDGET_DEMANDCHECK_PLAN_DETAIL_PRINT";
        public const string BUDGET_DEMANDCHECK_PLAN_DETAIL_EXCEL = "BUDGET_DEMANDCHECK_PLAN_DETAIL_EXCEL";
        public const string BUDGET_DEMANDCHECK_PLAN_DETAIL_BASE = "BUDGET_DEMANDCHECK_PLAN_DETAIL_BASE";

        public const string BUDGET_REVENUE_EXPENDITURE = "BUDGET_REVENUE_EXPENDITURE";
        public const string BUDGET_REVENUE_EXPENDITURE_DIVISION_INDEX = "BUDGET_REVENUE_EXPENDITURE_DIVISION_INDEX";
        public const string BUDGET_REVENUE_EXPENDITURE_REAL = "BUDGET_REVENUE_EXPENDITURE_REAL";
        public const string BUDGET_REVENUE_EXPENDITURE_PLAN = "BUDGET_REVENUE_EXPENDITURE_PLAN";
        public const string BUDGET_REVENUE_EXPENDITURE_IMPORT = "BUDGET_REVENUE_EXPENDITURE_IMPORT";
        public const string BUDGET_REVENUE_EXPENDITURE_APPROVE_ESTIMATION = "BUDGET_REVENUE_EXPENDITURE_APPROVE_ESTIMATION";


        public const string BUDGET_DEMANDCHECK_PLAN_DETAILCHILD_SAVE = "BUDGET_DEMANDCHECK_PLAN_DETAILCHILD_SAVE";
        public const string BUDGET_DEMANDCHECK_PLAN_DETAILCHILD_DELETE = "BUDGET_DEMANDCHECK_PLAN_DETAILCHILD_DELETE";
        public const string BUDGET_LEVEL_INDEX_ADD_EDIT = "BUDGET_LEVEL_INDEX_ADD_EDIT";
        public const string BUDGET_LEVEL_INDEX_LOCK = "BUDGET_LEVEL_INDEX_LOCK";
        public const string BUDGET_LEVEL_INDEX_DELETE = "BUDGET_LEVEL_INDEX_DELETE";
        public const string BUDGET_LEVEL_DETAIL_ADD = "BUDGET_LEVEL_DETAIL_ADD";
        public const string BUDGET_LEVEL_DETAIL_SAVE = "BUDGET_LEVEL_DETAIL_SAVE";
        public const string BUDGET_LEVEL_DETAIL_DELETE = "BUDGET_LEVEL_DETAIL_DELETE";
        public const string BUDGET_LEVEL_DETAIL_LOCK = "BUDGET_LEVEL_DETAIL_LOCK";
        public const string BUDGET_LEVEL_DETAIL_CHILD_SAVE = "BUDGET_LEVEL_DETAIL_CHILD_SAVE";
        public const string BUDGET_LEVEL_DETAIL_CHILD_DELETE = "BUDGET_LEVEL_DETAIL_CHILD_DELETE";

        public const string BUDGET_DEMANDCHECK = "BUDGET_DEMANDCHECK";
        public const string BUDGET_DEMANDCHECK_DEMAND = "BUDGET_DEMANDCHECK_DEMAND";
        public const string BUDGET_DEMANDCHECK_DEMAND_GUARANTEE = "BUDGET_DEMANDCHECK_DEMAND_GUARANTEE";
        public const string BUDGET_DEMANDCHECK_DEMAND_INDEX_ADD = "BUDGET_DEMANDCHECK_DEMAND_INDEX_ADD";
        public const string BUDGET_DEMANDCHECK_DEMAND_INDEX_EDIT = "BUDGET_DEMANDCHECK_DEMAND_INDEX_EDIT";
        public const string BUDGET_DEMANDCHECK_DEMAND_INDEX_DELETE = "BUDGET_DEMANDCHECK_DEMAND_INDEX_DELETE";
        public const string BUDGET_DEMANDCHECK_DEMAND_INDEX_LOCK = "BUDGET_DEMANDCHECK_DEMAND_INDEX_LOCK";
        public const string BUDGET_DEMANDCHECK_DEMAND_INDEX_SUMMARY = "BUDGET_DEMANDCHECK_DEMAND_INDEX_SUMMARY";
        public const string BUDGET_DEMANDCHECK_DEMAND_INDEX_EXPORT_SUMMARY = "BUDGET_DEMANDCHECK_DEMAND_INDEX_EXPORT_SUMMARY";
        public const string BUDGET_DEMANDCHECK_DEMAND_INDEX_REPORT = "BUDGET_DEMANDCHECK_DEMAND_INDEX_REPORT";
        public const string BUDGET_DEMANDCHECK_DEMAND_INDEX_EXCEL_IMPORT = "BUDGET_DEMANDCHECK_DEMAND_INDEX_EXCEL_IMPORT";
        public const string BUDGET_DEMANDCHECK_DEMAND_DETAIL_LOCK = "BUDGET_DEMANDCHECK_DEMAND_DETAIL_LOCK";
        public const string BUDGET_DEMANDCHECK_DEMAND_DETAIL_SAVE = "BUDGET_DEMANDCHECK_DEMAND_DETAIL_SAVE";
        public const string BUDGET_DEMANDCHECK_DEMAND_DETAIL_DELETE = "BUDGET_DEMANDCHECK_DEMAND_DETAIL_DELETE";
        public const string BUDGET_DEMANDCHECK_DEMAND_DETAIL_REPORT = "BUDGET_DEMANDCHECK_DEMAND_DETAIL_REPORT";
        public const string BUDGET_DEMANDCHECK_DEMAND_DETAIL_CAN_CU = "BUDGET_DEMANDCHECK_DEMAND_DETAIL_CAN_CU";

        public const string BUDGET_DEMANDCHECK_CHECK = "BUDGET_DEMANDCHECK_CHECK";
        public const string BUDGET_DEMANDCHECK_CHECK_INDEX_ADD = "BUDGET_DEMANDCHECK_CHECK_INDEX_ADD";
        public const string BUDGET_DEMANDCHECK_CHECK_INDEX_EDIT = "BUDGET_DEMANDCHECK_CHECK_INDEX_EDIT";
        public const string BUDGET_DEMANDCHECK_CHECK_INDEX_DELETE = "BUDGET_DEMANDCHECK_CHECK_INDEX_DELETE";
        public const string BUDGET_DEMANDCHECK_CHECK_INDEX_LOCK = "BUDGET_DEMANDCHECK_CHECK_INDEX_LOCK";
        public const string BUDGET_DEMANDCHECK_CHECK_INDEX_REPORT = "BUDGET_DEMANDCHECK_CHECK_INDEX_REPORT";
        public const string BUDGET_DEMANDCHECK_CHECK_INDEX_EXCEL_IMPORT = "BUDGET_DEMANDCHECK_CHECK_INDEX_EXCEL_IMPORT";
        public const string BUDGET_DEMANDCHECK_CHECK_DETAIL_LOCK = "BUDGET_DEMANDCHECK_CHECK_DETAIL_LOCK";
        public const string BUDGET_DEMANDCHECK_CHECK_DETAIL_SAVE = "BUDGET_DEMANDCHECK_CHECK_DETAIL_SAVE";
        public const string BUDGET_DEMANDCHECK_CHECK_DETAIL_DELETE = "BUDGET_DEMANDCHECK_CHECK_DETAIL_DELETE";
        public const string BUDGET_DEMANDCHECK_CHECK_DETAIL_REPORT = "BUDGET_DEMANDCHECK_CHECK_DETAIL_REPORT";

        public const string BUDGET_EXPERTISE = "BUDGET_EXPERTISE";
        public const string BUDGET_EXPERTISE_ADD_EDIT = "BUDGET_EXPERTISE_ADD_EDIT";
        public const string BUDGET_EXPERTISE_DELETE = "BUDGET_EXPERTISE_DELETE";
        public const string BUDGET_EXPERTISE_LOCK = "BUDGET_EXPERTISE_LOCK";
        public const string BUDGET_EXPERTISE_DETAIL_LOCK = "BUDGET_EXPERTISE_DETAIL_LOCK";
        public const string BUDGET_EXPERTISE_DETAIL_SAVE = "BUDGET_EXPERTISE_DETAIL_SAVE";
        public const string BUDGET_EXPERTISE_DETAIL_DELETE = "BUDGET_EXPERTISE_DETAIL_DELETE";

        public const string BUDGET_DEMANDCHECK_DISTRIBUTION = "BUDGET_DEMANDCHECK_DISTRIBUTION";
        public const string BUDGET_DEMANDCHECK_DISTRIBUTION_INDEX_REPORT = "BUDGET_DEMANDCHECK_DISTRIBUTION_INDEX_REPORT";
        public const string BUDGET_DEMANDCHECK_DISTRIBUTION_INDEX_EXCEL_EXPORT = "BUDGET_DEMANDCHECK_DISTRIBUTION_INDEX_EXCEL_EXPORT";
        public const string BUDGET_DEMANDCHECK_DISTRIBUTION_DETAIL_LOCK = "BUDGET_DEMANDCHECK_DISTRIBUTION_DETAIL_LOCK";
        public const string BUDGET_DEMANDCHECK_DISTRIBUTION_DETAIL_SAVE = "BUDGET_DEMANDCHECK_DISTRIBUTION_DETAIL_SAVE";
        public const string BUDGET_DEMANDCHECK_DISTRIBUTION_DETAIL_DELETE = "BUDGET_DEMANDCHECK_DISTRIBUTION_DETAIL_DELETE";
        public const string BUDGET_DEMANDCHECK_DISTRIBUTION_DETAIL_REPORT = "BUDGET_DEMANDCHECK_DISTRIBUTION_DETAIL_REPORT";

        public const string BUDGET_DEMANDCHECK_PLAN = "BUDGET_DEMANDCHECK_PLAN";
        public const string BUDGET_USE_DEMANDCHECK_PLAN_BEGIN_YEAR = "BUDGET_USE_DEMANDCHECK_PLAN_BEGIN_YEAR";
        public const string BUDGET_GUARANTEE_DEMANDCHECK_PLAN_BEGIN_YEAR = "BUDGET_GUARANTEE_DEMANDCHECK_PLAN_BEGIN_YEAR";
        public const string BUDGET_USE_DEMANDCHECK_PLAN = "BUDGET_USE_DEMANDCHECK_PLAN";
        public const string BUDGET_GUARANTEE_DEMANDCHECK_PLAN = "BUDGET_GUARANTEE_DEMANDCHECK_PLAN";

        public const string BUDGET_ESTIMATE = "BUDGET_ESTIMATE";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION = "BUDGET_ESTIMATE_RECEIVED_DIVISION";
        public const string BUDGET_ESTIMATE_DIVISION = "BUDGET_ESTIMATE_DIVISION";
        public const string BUDGET_ESTIMATE_DIVISION_GUARANTEE = "BUDGET_ESTIMATE_DIVISION_GUARANTEE";
        public const string BUDGET_ESTIMATE_HOSPITAL = "BUDGET_ESTIMATE_HOSPITAL";
        public const string BUDGET_ESTIMATE_ADJUSTED_ESTIMATE = "BUDGET_ESTIMATE_ADJUSTED_ESTIMATE";

        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_PANEL_ADD_EDIT = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_PANEL_ADD_EDIT";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_DELETE = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_DELETE";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_DETAIL = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_DETAIL";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_PANEL_AGGREGATE = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_PANEL_AGGREGATE";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_PRINT_REPORT = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_PRINT_REPORT";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_EXCEL = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_EXCEL";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_EXCEL_IMPORT = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_EXCEL_IMPORT";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_EXCEL_EXPORT = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_EXCEL_EXPORT";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_LOCK = "BUDGET_ESTIMATE_RECEIVED_DIVISION_INDEX_BTN_LOCK";

        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_ADD = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_ADD";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_DELETE = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_DELETE";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_LOCK = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_LOCK";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_PRINT_REPORT = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_PRINT_REPORT";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_DATA_SOURCE = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_DATA_SOURCE";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_DATA_INPUT = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_DATA_INPUT";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_SETTING_MLNS = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_SETTING_MLNS";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_DATA_IMPORT = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_DATA_IMPORT";
        public const string BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_MAP_DATA_IMPORT = "BUDGET_ESTIMATE_RECEIVED_DIVISION_DETAIL_BTN_MAP_DATA_IMPORT";

        public const string BUDGET_ESTIMATE_DIVISION_INDEX = "BUDGET_ESTIMATE_DIVISION_INDEX";
        public const string BUDGET_ESTIMATE_DIVISION_INDEX_PANEL_ADD_EDIT = "BUDGET_ESTIMATE_DIVISION_INDEX_PANEL_ADD_EDIT";
        public const string BUDGET_ESTIMATE_DIVISION_INDEX_BTN_DELETE = "BUDGET_ESTIMATE_DIVISION_INDEX_BTN_DELETE";
        public const string BUDGET_ESTIMATE_DIVISION_INDEX_BTN_DETAIL = "BUDGET_ESTIMATE_DIVISION_INDEX_BTN_DETAIL";
        public const string BUDGET_ESTIMATE_DIVISION_INDEX_PANEL_AGGREGATE = "BUDGET_ESTIMATE_DIVISION_INDEX_PANEL_AGGREGATE";
        public const string BUDGET_ESTIMATE_DIVISION_INDEX_BTN_PRINT_REPORT = "BUDGET_ESTIMATE_DIVISION_INDEX_BTN_PRINT_REPORT";
        public const string BUDGET_ESTIMATE_DIVISION_INDEX_BTN_EXCEL = "BUDGET_ESTIMATE_DIVISION_INDEX_BTN_EXCEL";
        public const string BUDGET_ESTIMATE_DIVISION_INDEX_BTN_EXCEL_IMPORT = "BUDGET_ESTIMATE_DIVISION_INDEX_BTN_EXCEL_IMPORT";
        public const string BUDGET_ESTIMATE_DIVISION_INDEX_BTN_EXCEL_EXPORT = "BUDGET_ESTIMATE_DIVISION_INDEX_BTN_EXCEL_EXPORT";
        public const string BUDGET_ESTIMATE_DIVISION_INDEX_BTN_LOCK = "BUDGET_ESTIMATE_DIVISION_INDEX_BTN_LOCK";

        public const string BUDGET_ESTIMATE_DIVISION_DETAIL = "BUDGET_ESTIMATE_DIVISION_DETAIL";
        public const string BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_ADD = "BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_ADD";
        public const string BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_DELETE = "BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_DELETE";
        public const string BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_LOCK = "BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_LOCK";
        public const string BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_PRINT_REPORT = "BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_PRINT_REPORT";
        public const string BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_DATA_ESTIMATE = "BUDGET_ESTIMATE_DIVISION_DETAIL_BTN_DATA_ESTIMATE";

        public const string BUDGET_SETTLEMENT = "BUDGET_SETTLEMENT";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET = "BUDGET_SETTLEMENT_DEFENSEBUDGET";
        public const string BUDGET_SETTLEMENT_DEFENSE_BUDGET = "BUDGET_SETTLEMENT_DEFENSE_BUDGET";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET = "BUDGET_SETTLEMENT_EXPENSEBUDGET";
        public const string BUDGET_SETTLEMENT_EXPENSE_BUDGET = "BUDGET_SETTLEMENT_EXPENSE_BUDGET";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET = "BUDGET_SETTLEMENT_FOREXBUDGET";
        public const string BUDGET_SETTLEMENT_FOREX_BUDGET = "BUDGET_SETTLEMENT_FOREX_BUDGET";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET = "BUDGET_SETTLEMENT_REGULARBUDGET";
        public const string BUDGET_SETTLEMENT_REGULAR_BUDGET = "BUDGET_SETTLEMENT_REGULAR_BUDGET";
        public const string BUDGET_SETTLEMENT_STATEBUDGET = "BUDGET_SETTLEMENT_STATEBUDGET";
        public const string BUDGET_SETTLEMENT_STATE_BUDGET = "BUDGET_SETTLEMENT_STATE_BUDGET";
        public const string BUDGET_SETTLEMENT_VOUCHERLIST = "BUDGET_SETTLEMENT_VOUCHERLIST";
        public const string BUDGET_SETTLEMENT_ARMY = "BUDGET_SETTLEMENT_ARMY";

        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_PANEL_ADD_EDIT = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_PANEL_ADD_EDIT";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_DELETE = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_DETAIL = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_DETAIL";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_PANEL_AGGREGATE = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_PANEL_AGGREGATE";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_PRINT_REPORT";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_EXCEL = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_EXCEL";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_EXCEL_IMPORT = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_EXCEL_IMPORT";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_EXCEL_EXPORT = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_EXCEL_EXPORT";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_LOCK = "BUDGET_SETTLEMENT_REGULARBUDGET_INDEX_BTN_LOCK";

        public const string BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL = "BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL_BTN_LOCK = "BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL_BTN_LOCK";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL_BTN_DELETE = "BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL_BTN_EXPLAIN = "BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL_BTN_EXPLAIN";
        public const string BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_REGULARBUDGET_DETAIL_BTN_PRINT_REPORT";

        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_PANEL_ADD_EDIT = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_PANEL_ADD_EDIT";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_DELETE = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_DETAIL = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_DETAIL";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_PANEL_AGGREGATE = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_PANEL_AGGREGATE";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_PRINT_REPORT";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_EXCEL = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_EXCEL";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_EXCEL_IMPORT = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_EXCEL_IMPORT";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_EXCEL_EXPORT = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_EXCEL_EXPORT";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_LOCK = "BUDGET_SETTLEMENT_DEFENSEBUDGET_INDEX_BTN_LOCK";

        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL = "BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL_BTN_LOCK = "BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL_BTN_LOCK";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL_BTN_DELETE = "BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL_BTN_EXPLAIN = "BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL_BTN_EXPLAIN";
        public const string BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_DEFENSEBUDGET_DETAIL_BTN_PRINT_REPORT";

        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_PANEL_ADD_EDIT = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_PANEL_ADD_EDIT";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_DELETE = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_DETAIL = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_DETAIL";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_PANEL_AGGREGATE = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_PANEL_AGGREGATE";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_PRINT_REPORT";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_EXCEL = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_EXCEL";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_EXCEL_IMPORT = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_EXCEL_IMPORT";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_EXCEL_EXPORT = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_EXCEL_EXPORT";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_LOCK = "BUDGET_SETTLEMENT_EXPENSEBUDGET_INDEX_BTN_LOCK";

        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL = "BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL_BTN_LOCK = "BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL_BTN_LOCK";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL_BTN_DELETE = "BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL_BTN_EXPLAIN = "BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL_BTN_EXPLAIN";
        public const string BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_EXPENSEBUDGET_DETAIL_BTN_PRINT_REPORT";

        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_PANEL_ADD_EDIT = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_PANEL_ADD_EDIT";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_DELETE = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_DETAIL = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_DETAIL";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_PANEL_AGGREGATE = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_PANEL_AGGREGATE";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_PRINT_REPORT";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_EXCEL = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_EXCEL";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_EXCEL_IMPORT = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_EXCEL_IMPORT";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_EXCEL_EXPORT = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_EXCEL_EXPORT";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_LOCK = "BUDGET_SETTLEMENT_FOREXBUDGET_INDEX_BTN_LOCK";

        public const string BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL = "BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL_BTN_LOCK = "BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL_BTN_LOCK";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL_BTN_DELETE = "BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL_BTN_EXPLAIN = "BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL_BTN_EXPLAIN";
        public const string BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_FOREXBUDGET_DETAIL_BTN_PRINT_REPORT";

        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX_PANEL_ADD_EDIT = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX_PANEL_ADD_EDIT";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_DELETE = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_DETAIL = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_DETAIL";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX_PANEL_AGGREGATE = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX_PANEL_AGGREGATE";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_PRINT_REPORT";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_EXCEL = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_EXCEL";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_EXCEL_IMPORT = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_EXCEL_IMPORT";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_EXCEL_EXPORT = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_EXCEL_EXPORT";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_LOCK = "BUDGET_SETTLEMENT_STATEBUDGET_INDEX_BTN_LOCK";

        public const string BUDGET_SETTLEMENT_STATEBUDGET_DETAIL = "BUDGET_SETTLEMENT_STATEBUDGET_DETAIL";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_DETAIL_BTN_LOCK = "BUDGET_SETTLEMENT_STATEBUDGET_DETAIL_BTN_LOCK";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_DETAIL_BTN_DELETE = "BUDGET_SETTLEMENT_STATEBUDGET_DETAIL_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_DETAIL_BTN_EXPLAIN = "BUDGET_SETTLEMENT_STATEBUDGET_DETAIL_BTN_EXPLAIN";
        public const string BUDGET_SETTLEMENT_STATEBUDGET_DETAIL_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_STATEBUDGET_DETAIL_BTN_PRINT_REPORT";

        public const string BUDGET_SETTLEMENT_VOUCHERLIST_INDEX = "BUDGET_SETTLEMENT_VOUCHERLIST_INDEX";
        public const string BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_PANEL_ADD_EDIT = "BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_PANEL_ADD_EDIT";
        public const string BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_BTN_DELETE = "BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_BTN_DETAIL = "BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_BTN_DETAIL";
        public const string BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_BTN_PRINT_REPORT";
        public const string BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_BTN_LOCK = "BUDGET_SETTLEMENT_VOUCHERLIST_INDEX_BTN_LOCK";

        public const string BUDGET_SETTLEMENT_VOUCHERLIST_DETAIL = "BUDGET_SETTLEMENT_VOUCHERLIST_DETAIL";
        public const string BUDGET_SETTLEMENT_VOUCHERLIST_DETAIL_BTN_DELETE = "BUDGET_SETTLEMENT_VOUCHERLIST_DETAIL_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_VOUCHERLIST_DETAIL_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_VOUCHERLIST_DETAIL_BTN_PRINT_REPORT";

        public const string BUDGET_SETTLEMENT_ARMY_INDEX = "BUDGET_SETTLEMENT_ARMY_INDEX";
        public const string BUDGET_SETTLEMENT_ARMY_INDEX_PANEL_ADD_EDIT = "BUDGET_SETTLEMENT_ARMY_INDEX_PANEL_ADD_EDIT";
        public const string BUDGET_SETTLEMENT_ARMY_INDEX_BTN_DELETE = "BUDGET_SETTLEMENT_ARMY_INDEX_BTN_DELETE";
        public const string BUDGET_SETTLEMENT_ARMY_INDEX_BTN_DETAIL = "BUDGET_SETTLEMENT_ARMY_INDEX_BTN_DETAIL";
        public const string BUDGET_SETTLEMENT_ARMY_INDEX_PANEL_AGGREGATE = "BUDGET_SETTLEMENT_ARMY_INDEX_PANEL_AGGREGATE";
        public const string BUDGET_SETTLEMENT_ARMY_INDEX_BTN_PRINT_REPORT = "BUDGET_SETTLEMENT_ARMY_INDEX_BTN_PRINT_REPORT";
        public const string BUDGET_SETTLEMENT_ARMY_INDEX_BTN_EXCEL = "BUDGET_SETTLEMENT_ARMY_INDEX_BTN_EXCEL";
        public const string BUDGET_SETTLEMENT_ARMY_INDEX_BTN_EXCEL_IMPORT = "BUDGET_SETTLEMENT_ARMY_INDEX_BTN_EXCEL_IMPORT";
        public const string BUDGET_SETTLEMENT_ARMY_INDEX_BTN_EXCEL_EXPORT = "BUDGET_SETTLEMENT_ARMY_INDEX_BTN_EXCEL_EXPORT";
        public const string BUDGET_SETTLEMENT_ARMY_INDEX_BTN_LOCK = "BUDGET_SETTLEMENT_ARMY_INDEX_BTN_LOCK";

        public const string BUDGET_SETTLEMENT_ARMY_DETAIL = "BUDGET_SETTLEMENT_ARMY_DETAIL";
        public const string BUDGET_SETTLEMENT_ARMY_DETAIL_BTN_LOCK = "BUDGET_SETTLEMENT_ARMY_DETAIL_BTN_LOCK";
        public const string BUDGET_SETTLEMENT_ARMY_DETAIL_BTN_EXPORT = "BUDGET_SETTLEMENT_ARMY_DETAIL_BTN_EXPORT";

        public const string INVESTMENT = "INVESTMENT";

        public const string INVESTMENT_MEDIUM_TERM_PLAN = "INVESTMENT_MEDIUM_TERM_PLAN";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_ADD = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_ADD";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_UPDATE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_UPDATE";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_MODIFY = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_MODIFY";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_DELETE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_DELETE";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_REPORT = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_REPORT";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_EXPORT = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_EXPORT";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_IMPORT = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_IMPORT";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_FILEATTACH = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_FILEATTACH";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_LOCK = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_LOCK";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_AGGREGATE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_INDEX_AGGREGATE";

        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DIALOG = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DIALOG";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DIALOG_SAVE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DIALOG_SAVE";

        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DETAIL = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DETAIL";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DETAIL_ADD = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DETAIL_ADD";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DETAIL_SAVE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DETAIL_SAVE";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DETAIL_DELETE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_SUGGESTION_DETAIL_DELETE";

        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_ADD = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_ADD";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_UPDATE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_UPDATE";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_MODIFY = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_MODIFY";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_DELETE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_DELETE";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_REPORT = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_REPORT";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_EXPORT = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_EXPORT";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_IMPORT = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_IMPORT";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_FILEATTACH = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_FILEATTACH";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_LOCK = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_INDEX_LOCK";

        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DIALOG = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DIALOG";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DIALOG_SAVE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DIALOG_SAVE";

        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DETAIL = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DETAIL";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DETAIL_CHOOSE_PROJECT = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DETAIL_CHOOSE_PROJECT";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DETAIL_SAVE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DETAIL_SAVE";
        public const string INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DETAIL_DELETE = "INVESTMENT_MEDIUM_TERM_PLAN_PLAN_MANAGER_APPROVED_DETAIL_DELETE";

        public const string INVESTMENT_STANDARD = "INVESTMENT_STANDARD";
        public const string INVESTMENT_STANDARD_ADVANCE_CAPITAL_APPROVED_INDEX = "INVESTMENT_STANDARD_ADVANCE_CAPITAL_APPROVED_INDEX";

        public const string INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU = "INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU";
        public const string INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX = "INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX";
        public const string INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX_ADD = "INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX_ADD";
        public const string INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX_UPDATE = "INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX_UPDATE";
        public const string INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX_MODIFY = "INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX_MODIFY";
        public const string INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX_DELETE = "INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_INDEX_DELETE";
        public const string INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_DIALOG = "INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_DIALOG";
        public const string INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_DIALOG_SAVE = "INVESTMENT_STANDARD_CHU_TRUONG_DAU_TU_DIALOG_SAVE";


        public const string INVESTMENT_STANDARD_GIAO_DU_TOAN_CHI_PHI = "INVESTMENT_STANDARD_GIAO_DU_TOAN_CHI_PHI";
        public const string INVESTMENT_STANDARD_GIAO_DU_TOAN_CHI_PHI_INDEX = "INVESTMENT_STANDARD_GIAO_DU_TOAN_CHI_PHI_INDEX";

        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN";
        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX_ADD = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX_ADD";
        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX_UPDATE = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX_UPDATE";
        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX_MODIFY = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX_MODIFY";
        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX_DELETE = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_INDEX_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_DIALOG = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_DIALOG";
        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_DIALOG_SAVE = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_DIALOG_SAVE";
        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_DIALOG_MODIFY = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_DIALOG_MODIFY";
        public const string INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_DIALOG_MODIFY_SAVE = "INVESTMENT_IMPLEMENTATION_PHE_DUYET_DU_AN_DIALOG_MODIFY_SAVE";

        public const string INVESTMENT_STANDARD_SYNTHETIC_YEAR_PLAN_INDEX = "INVESTMENT_STANDARD_SYNTHETIC_YEAR_PLAN_INDEX";

        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_ADD = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_ADD";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_UPDATE = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_UPDATE";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_MODIFY = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_MODIFY";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_DELETE = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_DELETE";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_EXPORT = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_EXPORT";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_IMPORT = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_IMPORT";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_REPORT = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_REPORT";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_LOCK = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_LOCK";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_AGGREGATE = "INVESTMENT_STANDARD_VON_NAM_DON_VI_INDEX_AGGREGATE";

        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_DIALOG = "INVESTMENT_STANDARD_VON_NAM_DON_VI_DIALOG";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_DIALOG_SAVE = "INVESTMENT_STANDARD_VON_NAM_DON_VI_DIALOG_SAVE";

        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_DETAIL = "INVESTMENT_STANDARD_VON_NAM_DON_VI_DETAIL";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_DETAIL_SAVE = "INVESTMENT_STANDARD_VON_NAM_DON_VI_DETAIL_SAVE";
        public const string INVESTMENT_STANDARD_VON_NAM_DON_VI_DETAIL_DELETE = "INVESTMENT_STANDARD_VON_NAM_DON_VI_DETAIL_DELETE";

        public const string INVESTMENT_STANDARD_YEAR_PLAN_INDEX = "INVESTMENT_STANDARD_YEAR_PLAN_INDEX";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_INDEX_ADD = "INVESTMENT_STANDARD_YEAR_PLAN_INDEX_ADD";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_INDEX_UPDATE = "INVESTMENT_STANDARD_YEAR_PLAN_INDEX_UPDATE";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_INDEX_MODIFY = "INVESTMENT_STANDARD_YEAR_PLAN_INDEX_MODIFY";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_INDEX_DELETE = "INVESTMENT_STANDARD_YEAR_PLAN_INDEX_DELETE";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_INDEX_EXPORT = "INVESTMENT_STANDARD_YEAR_PLAN_INDEX_EXPORT";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_INDEX_IMPORT = "INVESTMENT_STANDARD_YEAR_PLAN_INDEX_IMPORT";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_INDEX_REPORT = "INVESTMENT_STANDARD_YEAR_PLAN_INDEX_REPORT";

        public const string INVESTMENT_STANDARD_YEAR_PLAN_DIALOG = "INVESTMENT_STANDARD_YEAR_PLAN_DIALOG";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_DIALOG_SAVE = "INVESTMENT_STANDARD_YEAR_PLAN_DIALOG_SAVE";

        public const string INVESTMENT_STANDARD_YEAR_PLAN_DETAIL = "INVESTMENT_STANDARD_YEAR_PLAN_DETAIL";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_DETAIL_SAVE = "INVESTMENT_STANDARD_YEAR_PLAN_DETAIL_SAVE";
        public const string INVESTMENT_STANDARD_YEAR_PLAN_DETAIL_DELETE = "INVESTMENT_STANDARD_YEAR_PLAN_DETAIL_DELETE";

        public const string INVESTMENT_STANDARD_KE_HOACH_VON_UNG_DE_XUAT_INDEX = "INVESTMENT_STANDARD_KE_HOACH_VON_UNG_DE_XUAT_INDEX";

        public const string INVESTMENT_IMPLEMENTATION = "INVESTMENT_IMPLEMENTATION";
        public const string INVESTMENT_IMPLEMENTATION_APPROVED_OF_ADVANCED_CAPITAL_INDEX = "INVESTMENT_IMPLEMENTATION_APPROVED_OF_ADVANCED_CAPITAL_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX = "INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX";

        public const string INVESTMENT_IMPLEMENTATION_CONTRACT_INFO = "INVESTMENT_IMPLEMENTATION_CONTRACT_INFO";
        public const string INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX = "INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX_ADD = "INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX_ADD";
        public const string INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX_UPDATE = "INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX_UPDATE";
        public const string INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX_MODIFY = "INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX_MODIFY";
        public const string INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX_DELETE = "INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_INDEX_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_DIALOG = "INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_DIALOG";
        public const string INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_DIALOG_SAVE = "INVESTMENT_IMPLEMENTATION_CONTRACT_INFO_DIALOG_SAVE";

        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX";

        public const string INVESTMENT_IMPLEMENTATION_GOI_THAU = "INVESTMENT_IMPLEMENTATION_GOI_THAU";
        public const string INVESTMENT_IMPLEMENTATION_GOI_THAU_INDEX = "INVESTMENT_IMPLEMENTATION_GOI_THAU_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_GOI_THAU_INDEX_UPDATE = "INVESTMENT_IMPLEMENTATION_GOI_THAU_INDEX_UPDATE";
        public const string INVESTMENT_IMPLEMENTATION_GOI_THAU_INDEX_DELETE = "INVESTMENT_IMPLEMENTATION_GOI_THAU_INDEX_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_GOI_THAU_DIALOG = "INVESTMENT_IMPLEMENTATION_GOI_THAU_DIALOG";
        public const string INVESTMENT_IMPLEMENTATION_GOI_THAU_DIALOG_SAVE = "INVESTMENT_IMPLEMENTATION_GOI_THAU_DIALOG_SAVE";

        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY";
        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_ADD_EDIT = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_ADD_EDIT";
        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_INPUT_DETAIL = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_INPUT_DETAIL";
        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_DELETE = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_EXPORT = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_EXPORT";
        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_REPORT = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_INDEX_REPORT";
        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_DETAIL = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_DETAIL";
        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_DETAIL_SAVE = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_DETAIL_SAVE";
        public const string INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_DETAIL_DELETE = "INVESTMENT_IMPLEMENTATION_KE_HOACH_CHI_QUY_DETAIL_DELETE";

        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU";
        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX_ADD = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX_ADD";
        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX_UPDATE = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX_UPDATE";
        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX_MODIFY = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX_MODIFY";
        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX_DELETE = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_INDEX_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_DIALOG = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_DIALOG";
        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_DIALOG_SAVE = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_DIALOG_SAVE";
        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_DIALOG_MODIFY = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_DIALOG_MODIFY";
        public const string INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_DIALOG_MODIFY_SAVE = "INVESTMENT_IMPLEMENTATION_KH_LUA_CHON_NHA_THAU_DIALOG_MODIFY_SAVE";

        public const string INVESTMENT_IMPLEMENTATION_PROJECT_ALLOCATION_PRINT_REPORT = "INVESTMENT_IMPLEMENTATION_PROJECT_ALLOCATION_PRINT_REPORT";
        public const string INVESTMENT_IMPLEMENTATION_PROJECT_INFORMATION_PRINT_REPORT = "INVESTMENT_IMPLEMENTATION_PROJECT_INFORMATION_PRINT_REPORT";
        public const string INVESTMENT_IMPLEMENTATION_PRINT_REPORT_ANNUAL_BUDGET_ALLOCATION = "INVESTMENT_IMPLEMENTATION_PRINT_REPORT_ANNUAL_BUDGET_ALLOCATION";
        public const string INVESTMENT_IMPLEMENTATION_PRINT_REPORT_PROCESS_PROJECT = "INVESTMENT_IMPLEMENTATION_PRINT_REPORT_PROCESS_PROJECT";
        public const string INVESTMENT_IMPLEMENTATION_PRINT_REPORT_PROCESS_PROJECT_SEARCH = "INVESTMENT_IMPLEMENTATION_PRINT_REPORT_PROCESS_PROJECT_SEARCH";
        public const string INVESTMENT_IMPLEMENTATION_PRINT_REPORT_PROCESS_PROJECT_EXPORT = "INVESTMENT_IMPLEMENTATION_PRINT_REPORT_PROCESS_PROJECT_EXPORT";

        public const string INVESTMENT_IMPLEMENTATION_QLDA_INDEX = "INVESTMENT_IMPLEMENTATION_QLDA_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_THANH_TOAN_KHO_BAC_INDEX = "INVESTMENT_IMPLEMENTATION_THANH_TOAN_KHO_BAC_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_INDEX = "INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT = "INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_INDEX_ADD_EDIT = "INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_INDEX_ADD_EDIT";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_INDEX_INPUT_DETAIL = "INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_INDEX_INPUT_DETAIL";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_INDEX_INPUT_DELETE = "INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_INDEX_INPUT_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_DETAIL = "INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_DETAIL";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_DETAIL_SAVE = "INVESTMENT_IMPLEMENTATION_THONG_TRI_CAP_PHAT_DETAIL_SAVE";

        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN";
        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX_ADD = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX_ADD";
        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX_UPDATE = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX_UPDATE";
        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX_MODIFY = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX_MODIFY";
        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX_DELETE = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_INDEX_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_DIALOG = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_DIALOG";
        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_DIALOG_SAVE = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_DIALOG_SAVE";
        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_DIALOG_MODIFY = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_DIALOG_MODIFY";
        public const string INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_DIALOG_MODIFY_SAVE = "INVESTMENT_IMPLEMENTATION_TKTC_VA_TONG_DU_TOAN_DIALOG_MODIFY_SAVE";

        public const string INVESTMENT_IMPLEMENTATION_DU_TOAN_NSQP_NAM_PRINT_REPORT = "INVESTMENT_IMPLEMENTATION_DU_TOAN_NSQP_NAM_PRINT_REPORT";
        public const string INVESTMENT_IMPLEMENTATION_PROJECT_CAPITAL_ADJUSTMENT_REPORT = "INVESTMENT_IMPLEMENTATION_PROJECT_CAPITAL_ADJUSTMENT_REPORT";
        public const string INVESTMENT_IMPLEMENTATION_PRINT_REPORT_ADJUSTMENT_PLAN = "INVESTMENT_IMPLEMENTATION_PRINT_REPORT_ADJUSTMENT_PLAN";

        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_ADD_EDIT = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_ADD_EDIT";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_INPUT_DETAIL = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_INPUT_DETAIL";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_DELETE = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_EXCEL = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_EXCEL";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_IMPORT = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_IMPORT";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_LOCK = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_LOCK";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_SUMMARY = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_INDEX_SUMMARY";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_DETAIL = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_DETAIL";
        public const string INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_DETAIL_SAVE = "INVESTMENT_IMPLEMENTATION_QUYET_TOAN_VDT_DETAIL_SAVE";

        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_INDEX = "INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_BC_THEO_DOI_CHI_TIEU_CP_DU_AN = "INVESTMENT_IMPLEMENTATION_BC_THEO_DOI_CHI_TIEU_CP_DU_AN";
        public const string INVESTMENT_IMPLEMENTATION_BC_KQ_GIAI_NGAN_KPDT = "INVESTMENT_IMPLEMENTATION_BC_KQ_GIAI_NGAN_KPDT";

        public const string INVESTMENT_END_OF_INVESTMENT = "INVESTMENT_END_OF_INVESTMENT";
        public const string INVESTMENT_END_OF_INVESTMENT_ANNUAL_SETTLEMENT_INDEX = "INVESTMENT_END_OF_INVESTMENT_ANNUAL_SETTLEMENT_INDEX";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX";
        public const string INVESTMENT_END_OF_INVESTMENT_THONG_TRI_QUYET_TOAN_INDEX = "INVESTMENT_END_OF_INVESTMENT_THONG_TRI_QUYET_TOAN_INDEX";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN = "INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_INDEX_ADD_EDIT = "INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_INDEX_ADD_EDIT";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_INDEX_INPUT_DETAIL = "INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_INDEX_INPUT_DETAIL";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_INDEX_INPUT_DELETE = "INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_INDEX_INPUT_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_DETAIL = "INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_DETAIL";
        public const string INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_DETAIL_SAVE = "INVESTMENT_IMPLEMENTATION_THONG_TRI_QUYET_TOAN_DETAIL_SAVE";

        public const string INVESTMENT_END_OF_INVESTMENT_REPORT_SUMMARY_SETTLEMENT = "INVESTMENT_END_OF_INVESTMENT_REPORT_SUMMARY_SETTLEMENT";
        public const string INVESTMENT_END_OF_INVESTMENT_REPORT_PROJECT_APPLY_FILE = "INVESTMENT_END_OF_INVESTMENT_REPORT_PROJECT_APPLY_FILE";

        public const string INVESTMENT_INITIALIZATION = "INVESTMENT_INITIALIZATION";
        public const string INVESTMENT_INITIALIZATION_PROJECT = "INVESTMENT_INITIALIZATION_PROJECT";
        public const string INVESTMENT_INITIALIZATION_PROJECT_INDEX = "INVESTMENT_INITIALIZATION_PROJECT_INDEX";
        public const string INVESTMENT_INITIALIZATION_PROJECT_INDEX_ADD_EDIT = "INVESTMENT_INITIALIZATION_PROJECT_INDEX_ADD_EDIT";
        public const string INVESTMENT_INITIALIZATION_PROJECT_INDEX_DELETE = "INVESTMENT_INITIALIZATION_PROJECT_INDEX_DELETE";
        public const string INVESTMENT_INITIALIZATION_PROJECT_INDEX_EXPORT = "INVESTMENT_INITIALIZATION_PROJECT_INDEX_EXPORT";
        public const string INVESTMENT_INITIALIZATION_PROJECT_INDEX_IMPORT = "INVESTMENT_INITIALIZATION_PROJECT_INDEX_IMPORT";
        public const string INVESTMENT_INITIALIZATION_PROJECT_DETAIL = "INVESTMENT_INITIALIZATION_PROJECT_DETAIL";
        public const string INVESTMENT_INITIALIZATION_PROJECT_DETAIL_ADD = "INVESTMENT_INITIALIZATION_PROJECT_DETAIL_ADD";
        public const string INVESTMENT_INITIALIZATION_PROJECT_DETAIL_SAVE = "INVESTMENT_INITIALIZATION_PROJECT_DETAIL_SAVE";
        public const string INVESTMENT_INITIALIZATION_PROJECT_DETAIL_DELETE = "INVESTMENT_INITIALIZATION_PROJECT_DETAIL_DELETE";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_ADD_EDIT = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_ADD_EDIT";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_DELETE = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_DELETE";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_LOCK = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_LOCK";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_REPORT = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_REPORT";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_EXPORT = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_EXPORT";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_IMPORT = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_INDEX_IMPORT";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_DETAIL = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_DETAIL";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_DETAIL_SAVE = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_DETAIL_SAVE";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_DETAIL_ADD = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_DETAIL_ADD";
        public const string INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_DETAIL_DELETE = "INVESTMENT_END_OF_INVESTMENT_REQUEST_SETTLEMENT_DETAIL_DELETE";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_ADD_EDIT = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_ADD_EDIT";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_DELETE = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_DELETE";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_LOCK = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_LOCK";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_EXPORT = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_EXPORT";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_IMPORT = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_INDEX_IMPORT";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_DETAIL = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_DETAIL";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_DETAIL_SAVE = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_DETAIL_SAVE";
        public const string INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_DETAIL_DELETE = "INVESTMENT_END_OF_INVESTMENT_APPROVE_SETTLEMENT_DONE_DETAIL_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN = "INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN";

        public const string INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_ADD_EDIT = "INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_ADD_EDIT";
        public const string INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_DELETE = "INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_LOCK = "INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_LOCK";
        public const string INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_REPORT = "INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_REPORT";
        public const string INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_EXCEL = "INVESTMENT_IMPLEMENTATION_CAP_PHAT_THANH_TOAN_INDEX_EXCEL";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_ADD_EDIT = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_ADD_EDIT";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_DELETE = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_DELETE";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_LOCK = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_LOCK";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_REPORT = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_REPORT";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_EXCEL = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_INDEX_EXCEL";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_DETAIL = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_DETAIL";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_DETAIL_ADD = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_DETAIL_ADD";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_DETAIL_SAVE = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_DETAIL_SAVE";
        public const string INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_DETAIL_DELETE = "INVESTMENT_IMPLEMENTATION_DISBURSEMENT_PAYMENT_DETAIL_DELETE";

        public const string FOREX = "FOREX";
        public const string FOREX_PLAN = "FOREX_PLAN";
        public const string FOREX_PLAN_DETAIL = "FOREX_PLAN_DETAIL";
        public const string FOREX_PLAN_OVERVIEW = "FOREX_PLAN_OVERVIEW";
        public const string FOREX_ALLOCATION = "FOREX_ALLOCATION";
        public const string FOREX_PROJECT_CONTRACT = "FOREX_PROJECT_CONTRACT";
        public const string FOREX_PROJECT_CONTRACT_TONGHOP_TT_DUAN = "FOREX_PROJECT_CONTRACT_TONGHOP_TT_DUAN";
        public const string FOREX_PROJECT_APPROVAL = "FOREX_PROJECT_APPROVAL";
        public const string FOREX_INVESTMENT_POLICY = "FOREX_INVESTMENT_POLICY";
        public const string FOREX_DECISION_APPROVING_NEGOTIATION_RESULTS = "FOREX_DECISION_APPROVING_NEGOTIATION_RESULTS";
        public const string FOREX_DE_NGHI_THANH_TOAN = "FOREX_DE_NGHI_THANH_TOAN";
        public const string FOREX_BAO_CAO_TINH_HINH_THUC_HIEN_DU_AN = "FOREX_BAO_CAO_TINH_HINH_THUC_HIEN_DU_AN";

        public const string SALARY = "SALARY";
        public const string SALARY_CADRES = "SALARY_CADRES";
        public const string SALARY_CADRES_INDEX = "SALARY_CADRES_INDEX";
        public const string SALARY_CADRES_DETAIL = "SALARY_CADRES_DETAIL";
        public const string SALARY_CADRES_COPY = "SALARY_CADRES_COPY";
        public const string SALARY_CADRES_COPY_IN_MONTH = "SALARY_CADRES_COPY_IN_MONTH";
        public const string SALARY_CADRES_UPDATE_MULTI = "SALARY_CADRES_UPDATE_MULTI";
        public const string SALARY_CADRES_PRINT_FINANCE_REFERRAL = "SALARY_CADRES_PRINT_FINANCE_REFERRAL";
        public const string SALARY_CADRES_CAP_NHAT_LUONG_THUONG_THUE_TNCN = "SALARY_CADRES_CAP_NHAT_LUONG_THUONG_THUE_TNCN";
        public const string SALARY_CADRES_CAP_NHAT_LUONG_THUONG_THUE_TNCN_INDEX = "SALARY_CADRES_CAP_NHAT_LUONG_THUONG_THUE_TNCN_INDEX";

        public const string SALARY_REPORT = "SALARY_REPORT";
        public const string SALARY_REPORT_INDEX = "SALARY_REPORT_INDEX";

        public const string SALARY_MANAGEMENT = "SALARY_MANAGEMENT";
        public const string SALARY_MANAGEMENT_CALCULATE_SALARY_INDEX = "SALARY_MANAGEMENT_CALCULATE_SALARY_INDEX";
        public const string SALARY_MANAGEMENT_CALCULATE_SALARY_DIALOG = "SALARY_MANAGEMENT_CALCULATE_SALARY_DIALOG";
        public const string SALARY_MANAGEMENT_INSURANCE_SALARY_INDEX = "SALARY_MANAGEMENT_INSURANCE_SALARY_INDEX";
        public const string SALARY_MANAGEMENT_BACK_PAY_SALARY_INDEX = "SALARY_MANAGEMENT_BACK_PAY_SALARY_INDEX";
        public const string SALARY_MANAGEMENT_PURSUIT_SALARY_INDEX = "SALARY_MANAGEMENT_PURSUIT_SALARY_INDEX";
        public const string SALARY_MANAGEMENT_PURSUIT_SALARY_DETAIL = "SALARY_MANAGEMENT_PURSUIT_SALARY_DETAIL";
        public const string SALARY_MANAGEMENT_PURSUIT_SALARY_DIALOG = "SALARY_MANAGEMENT_PURSUIT_SALARY_DIALOG";
        public const string SALARY_MANAGEMENT_SALARY_COMPARISION_INDEX = "SALARY_MANAGEMENT_SALARY_COMPARISION_INDEX";
        public const string SALARY_MANAGEMENT_SALARY_COMPARISION_DIALOG = "SALARY_MANAGEMENT_SALARY_COMPARISION_DIALOG";
        public const string SALARY_MANAGEMENT_SALARY_DEVELOPMENTS_INDEX = "SALARY_MANAGEMENT_SALARY_DEVELOPMENTS_INDEX";
        public const string SALARY_MANAGEMENT_SALARY_TABLE_MONTH = "SALARY_MANAGEMENT_SALARY_TABLE_MONTH";
        public const string SALARY_MANAGEMENT_SALARY_TABLE_MONTH_INDEX = "SALARY_MANAGEMENT_SALARY_TABLE_MONTH_INDEX";
        public const string SALARY_MANAGEMENT_SALARY_TABLE_MONTH_DETAIL = "SALARY_MANAGEMENT_SALARY_TABLE_MONTH_DETAIL";
        public const string SALARY_MANAGEMENT_SALARY_TABLE_MONTH_DIALOG = "SALARY_MANAGEMENT_SALARY_TABLE_MONTH_DIALOG";
        public const string SALARY_MANAGEMENT_REPORTS = "SALARY_MANAGEMENT_REPORTS";
        public const string SALARY_MANAGEMENT_REPORTS_INDEX = "SALARY_MANAGEMENT_REPORTS_INDEX";
        public const string SALARY_MANAGEMENT_REPORTS_DIALOG = "SALARY_MANAGEMENT_REPORTS_DIALOG";
        public const string SALARY_MANAGEMENT_SALARY_MONTH_BHXH_INDEX = "SALARY_MANAGEMENT_SALARY_MONTH_BHXH_INDEX";

        public const string SALARY_SETTLEMENT = "SALARY_SETTLEMENT";
        public const string SALARY_SETTLEMENT_REGULAR_SETTLEMENT_INDEX = "SALARY_SETTLEMENT_REGULAR_SETTLEMENT_INDEX";
        public const string SALARY_SETTLEMENT_REGULAR_SETTLEMENT_DETAIL = "SALARY_SETTLEMENT_REGULAR_SETTLEMENT_DETAIL";
        public const string SALARY_SETTLEMENT_REGULAR_SETTLEMENT_DIALOG = "SALARY_SETTLEMENT_REGULAR_SETTLEMENT_DIALOG";
        public const string SALARY_SETTLEMENT_SALARY_CONFIGURATION_CONFIG_INDEX = "SALARY_SETTLEMENT_SALARY_CONFIGURATION_CONFIG_INDEX";
        public const string SALARY_SETTLEMENT_SETTLEMENT_NUMBER_INDEX = "SALARY_SETTLEMENT_SETTLEMENT_NUMBER_INDEX";
        public const string SALARY_SETTLEMENT_SETTLEMENT_NUMBER_DETAIL = "SALARY_SETTLEMENT_SETTLEMENT_NUMBER_DETAIL";
        public const string SALARY_SETTLEMENT_SETTLEMENT_NUMBER_DIALOG = "SALARY_SETTLEMENT_SETTLEMENT_NUMBER_DIALOG";
        public const string SALARY_SETTLEMENT_SETTLEMENT_NUMBER_INITIALIZATION = "SALARY_SETTLEMENT_SETTLEMENT_NUMBER_INITIALIZATION";

        public const string SALARY_PLAN = "SALARY_PLAN";
        public const string SALARY_PLAN_ALLOWENCE_ADJUSTMENT = "SALARY_PLAN_ALLOWENCE_ADJUSTMENT";
        public const string SALARY_PLAN_CADRES_PLAN = "SALARY_PLAN_CADRES_PLAN";

        public const string SALARY_QUAN_LY_LUONG_KE_HOACH = "SALARY_QUAN_LY_LUONG_KE_HOACH";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH = "SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_INDEX = "SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_INDEX";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_DIALOG = "SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_DIALOG";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_DETAIL = "SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_DETAIL";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_VOLATILITY = "SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_VOLATILITY";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_QUAN_SO = "SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_QUAN_SO";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_QUAN_SO_INDEX = "SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_QUAN_SO_INDEX";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH = "SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_INDEX = "SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_INDEX";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_DETAIL = "SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_DETAIL";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_COPY = "SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_COPY";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_DELETE = "SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_DELETE";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_CAU_HINH_THOI_HAN_TANG_QUAN_HAM = "SALARY_QUAN_LY_LUONG_KE_HOACH_CAU_HINH_THOI_HAN_TANG_QUAN_HAM";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_CAU_HINH_THOI_HAN_TANG_QUAN_HAM_INDEX = "SALARY_QUAN_LY_LUONG_KE_HOACH_CAU_HINH_THOI_HAN_TANG_QUAN_HAM_INDEX";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_PHU_CAP_THU_NHAP = "SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_PHU_CAP_THU_NHAP";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_PHU_CAP_THU_NHAP_INDEX = "SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_PHU_CAP_THU_NHAP_INDEX";

        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH = "SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH_INDEX = "SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH_INDEX";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH_DETAIL = "SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH_DETAIL";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH_COPY = "SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH_COPY";
        public const string SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH_DELETE = "SALARY_QUAN_LY_LUONG_KE_HOACH_CAN_BO_NGHI_HUU_KE_HOACH_DELETE";




        public const string SALARY_DANH_MUC_LUONG = "SALARY_DANH_MUC_LUONG";
        public const string SALARY_DANH_MUC_LUONG_CAU_HINH_HE_THONG = "SALARY_DANH_MUC_LUONG_CAU_HINH_HE_THONG";
        public const string SALARY_DANH_MUC_LUONG_DANH_MUC_CHUC_VU = "SALARY_DANH_MUC_LUONG_DANH_MUC_CHUC_VU";
        public const string SALARY_DANH_MUC_LUONG_DANH_MUC_KINH_PHI = "SALARY_DANH_MUC_LUONG_DANH_MUC_KINH_PHI";
        public const string SALARY_DANH_MUC_LUONG_DANH_MUC_THUE_TNCN = "SALARY_DANH_MUC_LUONG_DANH_MUC_THUE_TNCN";
        public const string SALARY_DANH_MUC_LUONG_DANH_MUC_TANG_GIAM = "SALARY_DANH_MUC_LUONG_DANH_MUC_TANG_GIAM";
        public const string SALARY_DANH_MUC_LUONG_DANH_MUC_PHU_CAP = "SALARY_DANH_MUC_LUONG_DANH_MUC_PHU_CAP";
        public const string SALARY_DANH_MUC_LUONG_DANH_MUC_CAP_BAC = "SALARY_DANH_MUC_LUONG_DANH_MUC_CAP_BAC";
        public const string SALARY_DANH_MUC_LUONG_DANH_MUC_DON_VI = "SALARY_DANH_MUC_LUONG_DANH_MUC_DON_VI";

        public const string SALARY_CHUYEN_DOI_DU_LIEU = "SALARY_CHUYEN_DOI_DU_LIEU";
        public const string SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG = "SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG";
        public const string SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_INDEX = "SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_INDEX";
        public const string SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_DIALOG = "SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_DIALOG";
        public const string SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_DETAIL = "SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_DETAIL";
        public const string SALARY_CHUYEN_DOI_DU_LIEU_ANH_XA_PHU_CAP = "SALARY_CHUYEN_DOI_DU_LIEU_ANH_XA_PHU_CAP";
        public const string SALARY_CHUYEN_DOI_DU_LIEU_ANH_XA_COT_DU_LIEU = "SALARY_CHUYEN_DOI_DU_LIEU_ANH_XA_COT_DU_LIEU";
        public const string SALARY_CHUYEN_DOI_DU_LIEU_KTDT = "SALARY_CHUYEN_DOI_DU_LIEU_KTDT";
        public const string SALARY_CHUYEN_DOI_DU_LIEU_KTDT_INDEX = "SALARY_CHUYEN_DOI_DU_LIEU_KTDT_INDEX";
        public const string SALARY_CHUYEN_DOI_DU_LIEU_KTDT_DIALOG = "SALARY_CHUYEN_DOI_DU_LIEU_KTDT_DIALOG";


        //Luong new
        public const string NEW_SALARY = "NEW_SALARY";
        public const string NEW_SALARY_CADRES = "NEW_SALARY_CADRES";
        public const string NEW_SALARY_CADRES_INDEX = "NEW_SALARY_CADRES_INDEX";
        public const string NEW_SALARY_CADRES_DETAIL = "NEW_SALARY_CADRES_DETAIL";
        public const string NEW_SALARY_CADRES_COPY = "NEW_SALARY_CADRES_COPY";
        public const string NEW_SALARY_CADRES_COPY_IN_MONTH = "NEW_SALARY_CADRES_COPY_IN_MONTH";
        public const string NEW_SALARY_CADRES_UPDATE_MULTI = "NEW_SALARY_CADRES_UPDATE_MULTI";
        public const string NEW_SALARY_CADRES_PRINT_FINANCE_REFERRAL = "NEW_SALARY_CADRES_PRINT_FINANCE_REFERRAL";
        public const string NEW_SALARY_CADRES_CAP_NHAT_LUONG_THUONG_THUE_TNCN = "NEW_SALARY_CADRES_CAP_NHAT_LUONG_THUONG_THUE_TNCN";
        public const string NEW_SALARY_CADRES_CAP_NHAT_LUONG_THUONG_THUE_TNCN_INDEX = "NEW_SALARY_CADRES_CAP_NHAT_LUONG_THUONG_THUE_TNCN_INDEX";

        public const string NEW_SALARY_REPORT = "NEW_SALARY_REPORT";
        public const string NEW_SALARY_REPORT_INDEX = "NEW_SALARY_REPORT_INDEX";

        public const string NEW_SALARY_MANAGEMENT = "NEW_SALARY_MANAGEMENT";
        public const string NEW_SALARY_MANAGEMENT_CALCULATE_SALARY_INDEX = "NEW_SALARY_MANAGEMENT_CALCULATE_SALARY_INDEX";
        public const string NEW_SALARY_MANAGEMENT_CALCULATE_SALARY_DIALOG = "NEW_SALARY_MANAGEMENT_CALCULATE_SALARY_DIALOG";
        public const string NEW_SALARY_MANAGEMENT_INSURANCE_SALARY_INDEX = "NEW_SALARY_MANAGEMENT_INSURANCE_SALARY_INDEX";
        public const string NEW_SALARY_MANAGEMENT_PURSUIT_SALARY_INDEX = "NEW_SALARY_MANAGEMENT_PURSUIT_SALARY_INDEX";
        public const string NEW_SALARY_MANAGEMENT_PURSUIT_SALARY_DETAIL = "NEW_SALARY_MANAGEMENT_PURSUIT_SALARY_DETAIL";
        public const string NEW_SALARY_MANAGEMENT_PURSUIT_SALARY_DIALOG = "NEW_SALARY_MANAGEMENT_PURSUIT_SALARY_DIALOG";
        public const string NEW_SALARY_MANAGEMENT_SALARY_COMPARISION_INDEX = "NEW_SALARY_MANAGEMENT_SALARY_COMPARISION_INDEX";
        public const string NEW_SALARY_MANAGEMENT_SALARY_COMPARISION_DIALOG = "NEW_SALARY_MANAGEMENT_SALARY_COMPARISION_DIALOG";
        public const string NEW_SALARY_MANAGEMENT_SALARY_DEVELOPMENTS_INDEX = "NEW_SALARY_MANAGEMENT_SALARY_DEVELOPMENTS_INDEX";
        public const string NEW_SALARY_MANAGEMENT_SALARY_TABLE_MONTH = "NEW_SALARY_MANAGEMENT_SALARY_TABLE_MONTH";
        public const string NEW_SALARY_MANAGEMENT_SALARY_TABLE_MONTH_INDEX = "NEW_SALARY_MANAGEMENT_SALARY_TABLE_MONTH_INDEX";
        public const string NEW_SALARY_MANAGEMENT_SALARY_TABLE_MONTH_DETAIL = "NEW_SALARY_MANAGEMENT_SALARY_TABLE_MONTH_DETAIL";
        public const string NEW_SALARY_MANAGEMENT_SALARY_TABLE_MONTH_DIALOG = "NEW_SALARY_MANAGEMENT_SALARY_TABLE_MONTH_DIALOG";
        public const string NEW_SALARY_MANAGEMENT_REPORTS = "NEW_SALARY_MANAGEMENT_REPORTS";
        public const string NEW_SALARY_MANAGEMENT_REPORTS_INDEX = "NEW_SALARY_MANAGEMENT_REPORTS_INDEX";
        public const string NEW_SALARY_MANAGEMENT_REPORTS_DIALOG = "NEW_SALARY_MANAGEMENT_REPORTS_DIALOG";
        public const string NEW_SALARY_MANAGEMENT_SALARY_MONTH_BHXH_INDEX = "NEW_SALARY_MANAGEMENT_SALARY_MONTH_BHXH_INDEX";

        public const string NEW_SALARY_SETTLEMENT = "NEW_SALARY_SETTLEMENT";
        public const string NEW_SALARY_SETTLEMENT_REGULAR_SETTLEMENT_INDEX = "NEW_SALARY_SETTLEMENT_REGULAR_SETTLEMENT_INDEX";
        public const string NEW_SALARY_SETTLEMENT_REGULAR_SETTLEMENT_DETAIL = "NEW_SALARY_SETTLEMENT_REGULAR_SETTLEMENT_DETAIL";
        public const string NEW_SALARY_SETTLEMENT_REGULAR_SETTLEMENT_DIALOG = "NEW_SALARY_SETTLEMENT_REGULAR_SETTLEMENT_DIALOG";
        public const string NEW_SALARY_SETTLEMENT_SALARY_CONFIGURATION_CONFIG_INDEX = "NEW_SALARY_SETTLEMENT_SALARY_CONFIGURATION_CONFIG_INDEX";
        public const string NEW_SALARY_SETTLEMENT_SETTLEMENT_NUMBER_INDEX = "NEW_SALARY_SETTLEMENT_SETTLEMENT_NUMBER_INDEX";
        public const string NEW_SALARY_SETTLEMENT_SETTLEMENT_NUMBER_DETAIL = "NEW_SALARY_SETTLEMENT_SETTLEMENT_NUMBER_DETAIL";
        public const string NEW_SALARY_SETTLEMENT_SETTLEMENT_NUMBER_DIALOG = "NEW_SALARY_SETTLEMENT_SETTLEMENT_NUMBER_DIALOG";
        public const string NEW_SALARY_SETTLEMENT_SETTLEMENT_NUMBER_INITIALIZATION = "NEW_SALARY_SETTLEMENT_SETTLEMENT_NUMBER_INITIALIZATION";

        public const string NEW_SALARY_PLAN = "NEW_SALARY_PLAN";
        public const string NEW_SALARY_PLAN_ALLOWENCE_ADJUSTMENT = "NEW_SALARY_PLAN_ALLOWENCE_ADJUSTMENT";
        public const string NEW_SALARY_PLAN_CADRES_PLAN = "NEW_SALARY_PLAN_CADRES_PLAN";

        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_INDEX = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_INDEX";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_DIALOG = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_DIALOG";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_DETAIL = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_DETAIL";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_VOLATILITY = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_BANG_LUONG_NAM_KH_VOLATILITY";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_QUAN_SO = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_QUAN_SO";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_QUAN_SO_INDEX = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_QUAN_SO_INDEX";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_INDEX = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_INDEX";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_DETAIL = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_DETAIL";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_COPY = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_COPY";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_DELETE = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DANH_SACH_DOI_TUONG_HUONG_LUONG_KE_HOACH_DELETE";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_CAU_HINH_THOI_HAN_TANG_QUAN_HAM = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_CAU_HINH_THOI_HAN_TANG_QUAN_HAM";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_CAU_HINH_THOI_HAN_TANG_QUAN_HAM_INDEX = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_CAU_HINH_THOI_HAN_TANG_QUAN_HAM_INDEX";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_PHU_CAP_THU_NHAP = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_PHU_CAP_THU_NHAP";
        public const string NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_PHU_CAP_THU_NHAP_INDEX = "NEW_SALARY_QUAN_LY_LUONG_KE_HOACH_DIEU_CHINH_PHU_CAP_THU_NHAP_INDEX";

        public const string NEW_SALARY_DANH_MUC_LUONG = "NEW_SALARY_DANH_MUC_LUONG";
        public const string NEW_SALARY_DANH_MUC_LUONG_CAU_HINH_HE_THONG = "NEW_SALARY_DANH_MUC_LUONG_CAU_HINH_HE_THONG";
        public const string NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_CHUC_VU = "NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_CHUC_VU";
        public const string NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_KINH_PHI = "NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_KINH_PHI";
        public const string NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_THUE_TNCN = "NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_THUE_TNCN";
        public const string NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_TANG_GIAM = "NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_TANG_GIAM";
        public const string NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_PHU_CAP = "NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_PHU_CAP";
        public const string NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_CAP_BAC = "NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_CAP_BAC";
        public const string NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_DON_VI = "NEW_SALARY_DANH_MUC_LUONG_DANH_MUC_DON_VI";

        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU = "NEW_SALARY_CHUYEN_DOI_DU_LIEU";
        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG = "NEW_SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG";
        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_INDEX = "NEW_SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_INDEX";
        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_DIALOG = "NEW_SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_DIALOG";
        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_DETAIL = "NEW_SALARY_CHUYEN_DOI_DU_LIEU_DOI_TUONG_DETAIL";
        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU_ANH_XA_PHU_CAP = "NEW_SALARY_CHUYEN_DOI_DU_LIEU_ANH_XA_PHU_CAP";
        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU_ANH_XA_COT_DU_LIEU = "NEW_SALARY_CHUYEN_DOI_DU_LIEU_ANH_XA_COT_DU_LIEU";
        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU_KTDT = "NEW_SALARY_CHUYEN_DOI_DU_LIEU_KTDT";
        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU_KTDT_INDEX = "NEW_SALARY_CHUYEN_DOI_DU_LIEU_KTDT_INDEX";
        public const string NEW_SALARY_CHUYEN_DOI_DU_LIEU_KTDT_DIALOG = "NEW_SALARY_CHUYEN_DOI_DU_LIEU_KTDT_DIALOG";


        public const string SOCIAL_INSURANCE = "SOCIAL_INSURANCE";
        public const string SOCIAL_INSURANCE_COMMON_PLAN = "SOCIAL_INSURANCE_COMMON_PLAN";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_ADD_EDIT = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_ADD_EDIT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_DELETE = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_DELETE";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_MODIFY = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_MODIFY";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_REPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_REPORT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_EXPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_EXPORT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_IMPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_IMPORT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_LOCK = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_LOCK";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_AGGREGATE = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_INDEX_AGGREGATE";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_DETAIL_SAVE = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_DETAIL_SAVE";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_DETAIL_REPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_CHI_DETAIL_REPORT";

        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_ADD_EDIT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_ADD_EDIT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_DELETE = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_DELETE";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_MODIFY = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_MODIFY";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_REPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_REPORT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_EXPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_EXPORT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_IMPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_IMPORT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_LOCK = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_LOCK";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_AGGREGATE = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_INDEX_AGGREGATE";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_DETAIL = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_DETAIL";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_DETAIL_SAVE = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_DETAIL_SAVE";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_DETAIL_REPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_DETAIL_REPORT";

        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_ADD_EDIT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_ADD_EDIT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_DELETE = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_DELETE";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_MODIFY = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_MODIFY";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_REPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_REPORT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_EXPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_EXPORT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_IMPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_IMPORT";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_LOCK = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_LOCK";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_AGGREGATE = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_INDEX_AGGREGATE";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_DETAIL = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_DETAIL";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_DETAIL_SAVE = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_DETAIL_SAVE";
        public const string SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_DETAIL_REPORT = "SOCIAL_INSURANCE_LAP_KE_HOACH_THU_MUA_BHYT_DETAIL_REPORT";

    }
}
